const test = require('node:test');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const http = require('node:http');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const {once} = require('node:events');
const {totp} = require('../security');
const {assertSafeOutboundUrl,privateAddress} = require('../network-security');
const {encryptBackup,decryptBackup} = require('../operations');
const {validatePassword} = require('../password-policy');
const {parseCSV} = require('../csv');

test('password policy enforces length, character diversity and common-password rejection',()=>{
 assert.equal(validatePassword('Ab1!aaaa').ok,false);
 assert.match(validatePassword('Ab1!aaaa').reason,/12 characters/);
 assert.equal(validatePassword('alllowercaseletters').ok,false);
 assert.match(validatePassword('alllowercaseletters').reason,/3 of/);
 assert.equal(validatePassword('Password123!').ok,false);
 assert.match(validatePassword('Password123!').reason,/too common/);
 assert.equal(validatePassword('A-secure-password9').ok,true);
});

test('CSV parser handles quoting, embedded commas and blank lines',()=>{
 const parsed=parseCSV('name,note\n"Acme, Inc.","Says ""hello"""\n\nSolo,\n');
 assert.deepEqual(parsed.headers,['name','note']);
 assert.equal(parsed.rows.length,2);
 assert.equal(parsed.rows[0].name,'Acme, Inc.');
 assert.equal(parsed.rows[0].note,'Says "hello"');
 assert.equal(parsed.rows[1].name,'Solo');
 assert.equal(parsed.rows[1].note,'');
 assert.deepEqual(parseCSV('').rows,[]);
 assert.throws(()=>parseCSV('a\n1\n2\n3\n',{maxRows:2}),/maximum/);
});

test('outbound URL policy blocks local and private networks',async()=>{
 assert.equal(privateAddress('127.0.0.1'),true);
 assert.equal(privateAddress('10.20.30.40'),true);
 assert.equal(privateAddress('169.254.169.254'),true);
 assert.equal(privateAddress('8.8.8.8'),false);
 await assert.rejects(()=>assertSafeOutboundUrl('http://127.0.0.1/admin'),/HTTPS/);
 await assert.rejects(()=>assertSafeOutboundUrl('https://127.0.0.1/admin'),/Private network/);
});

test('offsite backup encryption round trips and rejects the wrong key',()=>{
 const previous=process.env.BACKUP_ENCRYPTION_KEY;process.env.BACKUP_ENCRYPTION_KEY='test-backup-key-that-is-longer-than-32-characters';
 try{const source=Buffer.from('sqlite backup bytes'),encrypted=encryptBackup(source);assert.notDeepEqual(encrypted,source);assert.deepEqual(decryptBackup(encrypted),source);process.env.BACKUP_ENCRYPTION_KEY='different-backup-key-that-is-long-enough';assert.throws(()=>decryptBackup(encrypted));}finally{if(previous===undefined)delete process.env.BACKUP_ENCRYPTION_KEY;else process.env.BACKUP_ENCRYPTION_KEY=previous}
});

test('required email verification blocks financial mutations',async t=>{
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'ledgeriq-verify-test-')),port=34000+Math.floor(Math.random()*1000),origin=`http://localhost:${port}`;
 const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,NODE_ENV:'development',PORT:String(port),APP_ORIGIN:origin,REQUIRE_EMAIL_VERIFICATION:'true',SESSION_SECRET:'verification-test-secret-longer-than-32-characters',INTEGRATION_ENCRYPTION_KEY:'verification-integration-key-longer-than-32-characters',LEDGERIQ_DATA_DIR:path.join(temp,'data'),LEDGERIQ_BACKUP_DIR:path.join(temp,'backups'),OBJECT_STORAGE_PATH:path.join(temp,'documents')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',data=>process.stderr.write(data));t.after(async()=>{child.kill();await once(child,'exit');fs.rmSync(temp,{recursive:true,force:true})});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('verification server start timeout')),5000);child.stdout.on('data',data=>{if(String(data).includes('ledgerIQ running')){clearTimeout(timer);resolve()}});child.on('exit',code=>reject(new Error(`verification server exited ${code}`)))});
 const response=await fetch(origin+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({email:'unverified@example.com',password:'A-secure-password9',companyName:'Verify Co',ownerName:'Una Verified'})}),cookie=response.headers.get('set-cookie')?.split(';')[0];assert.equal(response.status,201);const registerData=await response.json();assert.ok(registerData.verificationToken);
 const blocked=await fetch(origin+'/api/clients',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie},body:JSON.stringify({name:'Blocked Client'})});assert.equal(blocked.status,403);assert.match((await blocked.json()).error,/Verify your email/);
 const unverifiedLogin=await fetch(origin+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({email:'unverified@example.com',password:'A-secure-password9'})});assert.equal(unverifiedLogin.status,200,'login must never be blocked by unverified email');
 const resend=await fetch(origin+'/api/security/verify/resend',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie},body:'{}'});assert.equal(resend.status,200);const resendData=await resend.json();assert.ok(resendData.token);assert.notEqual(resendData.token,registerData.verificationToken);
 const staleToken=await fetch(origin+'/api/auth/verify-email',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({token:registerData.verificationToken})});assert.equal(staleToken.status,400,'a token invalidated by resend must not verify');
 const freshToken=await fetch(origin+'/api/auth/verify-email',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({token:resendData.token})});assert.equal(freshToken.status,200);
 const replayedToken=await fetch(origin+'/api/auth/verify-email',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({token:resendData.token})});assert.equal(replayedToken.status,400,'a used verification token must not be replayable');
});

test('data retention purge deletes only tenants that opted in and are actually past their grace period',async t=>{
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'ledgeriq-retention-test-')),port=35000+Math.floor(Math.random()*1000),origin=`http://localhost:${port}`,webhookSecret='retention-test-billing-webhook-secret';
 const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,NODE_ENV:'test',PORT:String(port),APP_ORIGIN:origin,BILLING_WEBHOOK_SECRET:webhookSecret,SESSION_SECRET:'retention-test-secret-longer-than-32-characters',INTEGRATION_ENCRYPTION_KEY:'retention-integration-key-longer-than-32-characters',LEDGERIQ_DATA_DIR:path.join(temp,'data'),LEDGERIQ_BACKUP_DIR:path.join(temp,'backups'),OBJECT_STORAGE_PATH:path.join(temp,'documents')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',data=>process.stderr.write(data));t.after(async()=>{child.kill();await once(child,'exit');fs.rmSync(temp,{recursive:true,force:true})});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('retention server start timeout')),5000);child.stdout.on('data',data=>{if(String(data).includes('ledgerIQ running')){clearTimeout(timer);resolve()}});child.on('exit',code=>reject(new Error(`retention server exited ${code}`)))});
 async function request(route,{cookie,...options}={}){const response=await fetch(origin+route,{...options,headers:{'Content-Type':'application/json',Origin:origin,...(cookie?{Cookie:cookie}:{}),...(options.headers||{})}}),data=await response.json().catch(()=>({}));return{response,data,cookie:response.headers.get('set-cookie')?.split(';')[0]}}
 async function cancelViaWebhook(email){const body=JSON.stringify({email,status:'cancelled'}),signature=crypto.createHmac('sha256',webhookSecret).update(body).digest('hex');const result=await fetch(origin+'/api/billing/webhook',{method:'POST',headers:{'Content-Type':'application/json','x-ledgeriq-signature':signature},body});assert.equal(result.status,200)}
 async function reactivateViaWebhook(email){const body=JSON.stringify({email,status:'active'}),signature=crypto.createHmac('sha256',webhookSecret).update(body).digest('hex');const result=await fetch(origin+'/api/billing/webhook',{method:'POST',headers:{'Content-Type':'application/json','x-ledgeriq-signature':signature},body});assert.equal(result.status,200)}

 const purged=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'purged@example.com',password:'A-secure-password9',companyName:'Purged Co',ownerName:'Pat Purged'})});assert.equal(purged.response.status,201);
 const survivorDefault=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'survivor-default@example.net',password:'A-secure-password9',companyName:'Survivor Default Co',ownerName:'Sam Survivor'})});assert.equal(survivorDefault.response.status,201);
 const survivorReactivated=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'survivor-reactivated@example.org',password:'A-secure-password9',companyName:'Survivor Reactivated Co',ownerName:'Robin Survivor'})});assert.equal(survivorReactivated.response.status,201);

 const invalidRetention=await request('/api/profile',{cookie:purged.cookie,method:'PUT',body:JSON.stringify({companyName:'Purged Co',ownerName:'Pat Purged',email:'purged@example.com',currency:'ZAR',retentionDays:5})});assert.equal(invalidRetention.response.status,400,'only the fixed retention presets are valid');

 await cancelViaWebhook('purged@example.com');
 const setRetention=await request('/api/profile',{cookie:purged.cookie,method:'PUT',body:JSON.stringify({companyName:'Purged Co',ownerName:'Pat Purged',email:'purged@example.com',currency:'ZAR',retentionDays:0})});assert.equal(setRetention.response.status,200);assert.equal(setRetention.data.profile.dataRetentionDays,0);

 await cancelViaWebhook('survivor-default@example.net');

 await cancelViaWebhook('survivor-reactivated@example.org');
 await reactivateViaWebhook('survivor-reactivated@example.org');
 const reactivatedRetention=await request('/api/profile',{cookie:survivorReactivated.cookie,method:'PUT',body:JSON.stringify({companyName:'Survivor Reactivated Co',ownerName:'Robin Survivor',email:'survivor-reactivated@example.org',currency:'ZAR',retentionDays:0})});assert.equal(reactivatedRetention.response.status,200,'a reactivated tenant can still update its profile normally');

 const maintenance=await request('/api/test/run-maintenance',{method:'POST',body:'{}'});assert.equal(maintenance.response.status,200);

 assert.equal((await request('/api/bootstrap',{cookie:purged.cookie})).response.status,401,'a cancelled tenant with retentionDays=0 must be purged');
 assert.equal((await request('/api/bootstrap',{cookie:survivorDefault.cookie})).response.status,200,'a cancelled tenant that never opted into a retention window must default to never-purge');
 assert.equal((await request('/api/bootstrap',{cookie:survivorReactivated.cookie})).response.status,200,'reactivation must clear cancelled_at so retentionDays=0 does not retroactively purge it');
});

test('phone/SMS OTP: enrollment and login second factor work end-to-end against a stub provider',async t=>{
 const sentMessages=[];
 const smsServer=http.createServer((req,res)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{sentMessages.push(JSON.parse(raw||'{}'));res.writeHead(200,{'Content-Type':'application/json'});res.end('{}')})});
 await new Promise(resolve=>smsServer.listen(0,resolve));
 const smsPort=smsServer.address().port;
 t.after(()=>new Promise(resolve=>smsServer.close(resolve)));
 function latestCode(){const last=sentMessages[sentMessages.length-1];const match=/code is (\d{6})/.exec(last?.message||'');if(!match)throw new Error(`no OTP code found in last SMS: ${JSON.stringify(last)}`);return match[1]}

 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'ledgeriq-otp-test-')),port=36000+Math.floor(Math.random()*1000),origin=`http://localhost:${port}`;
 const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,NODE_ENV:'test',PORT:String(port),APP_ORIGIN:origin,SMS_PROVIDER_API_URL:`http://localhost:${smsPort}`,SMS_PROVIDER_API_KEY:'test-sms-key',SESSION_SECRET:'otp-test-secret-longer-than-32-characters',INTEGRATION_ENCRYPTION_KEY:'otp-test-integration-key-longer-than-32-characters',LEDGERIQ_DATA_DIR:path.join(temp,'data'),LEDGERIQ_BACKUP_DIR:path.join(temp,'backups'),OBJECT_STORAGE_PATH:path.join(temp,'documents')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',data=>process.stderr.write(data));t.after(async()=>{child.kill();await once(child,'exit');fs.rmSync(temp,{recursive:true,force:true})});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('otp server start timeout')),5000);child.stdout.on('data',data=>{if(String(data).includes('ledgerIQ running')){clearTimeout(timer);resolve()}});child.on('exit',code=>reject(new Error(`otp server exited ${code}`)))});
 async function request(route,{cookie,...options}={}){const response=await fetch(origin+route,{...options,headers:{'Content-Type':'application/json',Origin:origin,...(cookie?{Cookie:cookie}:{}),...(options.headers||{})}}),data=await response.json().catch(()=>({}));return{response,data,cookie:response.headers.get('set-cookie')?.split(';')[0]}}

 const registered=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'phoneowner@example.com',password:'A-secure-password9',companyName:'Phone Co',ownerName:'Pat Phone'})});assert.equal(registered.response.status,201);
 const plainLogin=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'phoneowner@example.com',password:'A-secure-password9'})});assert.equal(plainLogin.response.status,200);assert.equal(plainLogin.data.otpRequired,undefined,'OTP must not be required before it is enabled');

 const setup=await request('/api/security/phone/setup',{cookie:registered.cookie,method:'POST',body:JSON.stringify({phone:'+27821234567'})});assert.equal(setup.response.status,200);
 assert.equal(sentMessages.length,1);assert.equal(sentMessages[0].to,'+27821234567');
 const wrongEnable=await request('/api/security/phone/enable',{cookie:registered.cookie,method:'POST',body:JSON.stringify({code:'000000'})});assert.equal(wrongEnable.response.status,400,'a wrong enrollment code must be rejected');
 const enable=await request('/api/security/phone/enable',{cookie:registered.cookie,method:'POST',body:JSON.stringify({code:latestCode()})});assert.equal(enable.response.status,200);
 const statusAfterEnable=await request('/api/security/status',{cookie:registered.cookie});assert.equal(statusAfterEnable.data.smsOtpEnabled,1);assert.ok(statusAfterEnable.data.phoneVerifiedAt);

 const gatedLogin=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'phoneowner@example.com',password:'A-secure-password9'})});assert.equal(gatedLogin.response.status,200);assert.equal(gatedLogin.data.otpRequired,true);assert.ok(gatedLogin.data.challengeId);assert.equal(gatedLogin.cookie,undefined,'no session cookie until the OTP step also succeeds');
 assert.equal(sentMessages.length,2);

 const wrongVerify=await request('/api/auth/otp/verify',{method:'POST',body:JSON.stringify({challengeId:gatedLogin.data.challengeId,code:'000000'})});assert.equal(wrongVerify.response.status,401);
 const verify=await request('/api/auth/otp/verify',{method:'POST',body:JSON.stringify({challengeId:gatedLogin.data.challengeId,code:latestCode()})});assert.equal(verify.response.status,200);assert.match(verify.cookie,/ledgeriq_session/);
 assert.equal((await request('/api/me',{cookie:verify.cookie})).response.status,200,'the session issued after OTP verification must actually work');

 const replay=await request('/api/auth/otp/verify',{method:'POST',body:JSON.stringify({challengeId:gatedLogin.data.challengeId,code:latestCode()})});assert.equal(replay.response.status,401,'a consumed OTP code must not be replayable');

 const disable=await request('/api/security/phone/disable',{cookie:verify.cookie,method:'POST',body:JSON.stringify({password:'A-secure-password9'})});assert.equal(disable.response.status,200);
 const loginAfterDisable=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'phoneowner@example.com',password:'A-secure-password9'})});assert.equal(loginAfterDisable.response.status,200);assert.equal(loginAfterDisable.data.otpRequired,undefined,'disabling SMS OTP must remove the login gate');
});

test('registration warns about a likely-duplicate business by email domain, without leaking existing tenant names',async t=>{
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'ledgeriq-domain-test-')),port=37000+Math.floor(Math.random()*1000),origin=`http://localhost:${port}`;
 const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,NODE_ENV:'test',PORT:String(port),APP_ORIGIN:origin,SESSION_SECRET:'domain-test-secret-longer-than-32-characters',INTEGRATION_ENCRYPTION_KEY:'domain-test-integration-key-longer-than-32-characters',LEDGERIQ_DATA_DIR:path.join(temp,'data'),LEDGERIQ_BACKUP_DIR:path.join(temp,'backups'),OBJECT_STORAGE_PATH:path.join(temp,'documents')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',data=>process.stderr.write(data));t.after(async()=>{child.kill();await once(child,'exit');fs.rmSync(temp,{recursive:true,force:true})});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('domain server start timeout')),5000);child.stdout.on('data',data=>{if(String(data).includes('ledgerIQ running')){clearTimeout(timer);resolve()}});child.on('exit',code=>reject(new Error(`domain server exited ${code}`)))});
 async function request(route,{cookie,...options}={}){const response=await fetch(origin+route,{...options,headers:{'Content-Type':'application/json',Origin:origin,...(cookie?{Cookie:cookie}:{}),...(options.headers||{})}}),data=await response.json().catch(()=>({}));return{response,data,cookie:response.headers.get('set-cookie')?.split(';')[0]}}

 const first=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'alice@acme-test.example',password:'A-secure-password9',companyName:'Acme HQ',ownerName:'Alice'})});assert.equal(first.response.status,201);

 const warned=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'bob@acme-test.example',password:'A-secure-password9',companyName:'Definitely Not Acme',ownerName:'Bob'})});
 assert.equal(warned.response.status,200);assert.equal(warned.data.domainWarning,true);assert.equal(warned.cookie,undefined,'no session must be created while the warning is unresolved');
 assert.doesNotMatch(warned.data.message,/Acme HQ/,'the warning must never echo back an existing tenant name');

 const stillNoAccount=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'bob@acme-test.example',password:'A-secure-password9'})});assert.equal(stillNoAccount.response.status,401,'the warned registration attempt must not have silently created an account');

 const confirmed=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'bob@acme-test.example',password:'A-secure-password9',companyName:'Definitely Not Acme',ownerName:'Bob',confirmNewWorkspace:true})});assert.equal(confirmed.response.status,201);assert.match(confirmed.cookie,/ledgeriq_session/);

 const gmailFirst=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'carol@gmail.com',password:'A-secure-password9',companyName:"Carol's Studio",ownerName:'Carol'})});assert.equal(gmailFirst.response.status,201);
 const gmailSecond=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'dave@gmail.com',password:'A-secure-password9',companyName:"Dave's Studio",ownerName:'Dave'})});assert.equal(gmailSecond.response.status,201,'free/consumer email domains must never trigger the duplicate-workspace warning');
});

async function coreFlow(t,databaseUrl=''){
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'ledgeriq-test-')),port=32000+Math.floor(Math.random()*2000);
 const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,NODE_ENV:'test',DATABASE_URL:databaseUrl,DATABASE_RESET_FOR_TESTS:databaseUrl?'true':'false',DISABLE_AUTOMATED_BACKUPS:databaseUrl?'true':'false',PORT:String(port),APP_ORIGIN:`http://localhost:${port}`,SESSION_SECRET:'test-secret-that-is-longer-than-32-characters',INTEGRATION_ENCRYPTION_KEY:'test-integration-secret-longer-than-32-characters',BILLING_WEBHOOK_SECRET:'test-billing-webhook-secret',LEDGERIQ_DATA_DIR:path.join(temp,'data'),LEDGERIQ_BACKUP_DIR:path.join(temp,'backups'),OBJECT_STORAGE_PATH:path.join(temp,'documents')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',data=>process.stderr.write(data));
 t.after(async()=>{child.kill();await once(child,'exit');fs.rmSync(temp,{recursive:true,force:true})});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('server start timeout')),databaseUrl?15000:5000);child.stdout.on('data',data=>{if(String(data).includes('ledgerIQ running')){clearTimeout(timer);resolve()}});child.on('exit',code=>reject(new Error(`server exited ${code}`)))});
 const base=`http://localhost:${port}`;
 async function request(route,{cookie,...options}={}){const response=await fetch(base+route,{...options,headers:{'Content-Type':'application/json',Origin:base,...(cookie?{Cookie:cookie}:{}),...(options.headers||{})}}),data=await response.json();return{response,data,cookie:response.headers.get('set-cookie')?.split(';')[0]}}
 async function rawRequest(route,{cookie,...options}={}){return fetch(base+route,{...options,headers:{Origin:base,...(cookie?{Cookie:cookie}:{}),...(options.headers||{})}})}
 async function assertPdf(response){assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'application/pdf');assert.equal(Buffer.from(await response.arrayBuffer()).subarray(0,5).toString(),'%PDF-')}
 const landing=await fetch(base);assert.equal(landing.status,200);const landingHtml=await landing.text();assert.match(landingHtml,/ledgerIQ Business/);assert.match(landingHtml,/R5,990\/year/);assert.match(landingHtml,/R<\/span>10k/);assert.equal(landing.headers.get('x-frame-options'),'DENY');assert.equal((await fetch(base+'/developers')).status,200);
 for(const sensitive of ['/server.js','/enterprise.js','/package.json','/.env','/data/ledgeriq.sqlite','/backups/ledgeriq.sqlite'])assert.equal((await fetch(base+sensitive)).status,404,`${sensitive} must not be public`);
 const health=await request('/api/health');assert.equal(health.data.ok,true);const ready=await request('/api/ready');assert.equal(ready.response.status,200);assert.equal(ready.data.database,true);assert.equal((await request('/api/auth/register',{method:'POST',body:'{'})).response.status,400);
 const weakPassword=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'weak@example.com',password:'Ab1!aaaa',companyName:'Weak Co',ownerName:'Weak Owner'})});assert.equal(weakPassword.response.status,400);assert.match(weakPassword.data.error,/12 characters/);
 const first=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'A-secure-password9',companyName:'Acme Studio',ownerName:'Ada Owner'})});assert.equal(first.response.status,201);assert.match(first.cookie,/ledgeriq_session/);
 assert.ok(first.data.verificationToken);assert.equal((await request('/api/auth/verify-email',{method:'POST',body:JSON.stringify({token:first.data.verificationToken})})).response.status,200);const securityStatus=await request('/api/security/status',{cookie:first.cookie});assert.ok(securityStatus.data.emailVerifiedAt);assert.equal(securityStatus.data.smsOtpEnabled,0);
 const phoneSetupUnconfigured=await request('/api/security/phone/setup',{cookie:first.cookie,method:'POST',body:JSON.stringify({phone:'+27821234567'})});assert.equal(phoneSetupUnconfigured.response.status,503,'phone OTP must be inert when no SMS provider is configured');
 const billingBody=JSON.stringify({email:'owner@example.com',status:'active'}),billingSignature=crypto.createHmac('sha256','test-billing-webhook-secret').update(billingBody).digest('hex'),billingOptions={method:'POST',headers:{'x-ledgeriq-signature':billingSignature},body:billingBody};const billed=await request('/api/billing/webhook',billingOptions);assert.equal(billed.response.status,200);assert.equal(billed.data.processed,true);const replayedBilling=await request('/api/billing/webhook',billingOptions);assert.equal(replayedBilling.data.replayed,true);
 const second=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'other@example.net',password:'Another-secure-password9',companyName:'Other Co',ownerName:'Other Owner'})});assert.equal(second.response.status,201);
 const client=await request('/api/clients',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Client One',email:'client@example.com',address:'Cape Town',vatNumber:'4123456789'})});assert.equal(client.response.status,201);
 const invoice=await request('/api/invoices',{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'INV-0001',clientId:client.data.id,issue:'2026-08-15',due:'2026-08-30',taxRate:15,discount:100,notes:'Thanks',paymentDetails:'EFT',items:[{description:'Design',qty:2,rate:1000}]})});assert.equal(invoice.response.status,201);
 await assertPdf(await rawRequest(`/api/invoices/${invoice.data.id}/pdf`,{cookie:first.cookie}));
 assert.equal((await rawRequest(`/api/invoices/${invoice.data.id}/pdf`,{cookie:second.cookie})).status,404,'invoice PDFs must be tenant-isolated');
 const expense=await request('/api/expenses',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'BILL-0001',vendor:'Cloud Co',category:'Software',date:'2026-08-15',due:'2026-08-20',amount:250,status:'due',notes:'Hosting'})});assert.equal(expense.response.status,201);

 const payInvoice=await request('/api/invoices',{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'INV-PAY-0001',clientId:client.data.id,issue:'2026-08-15',due:'2026-08-30',taxRate:15,discount:100,items:[{description:'Design',qty:2,rate:1000}]})});assert.equal(payInvoice.response.status,201);
 const badPayment=await request(`/api/invoices/${payInvoice.data.id}/payments`,{cookie:first.cookie,method:'POST',body:JSON.stringify({amount:-5})});assert.equal(badPayment.response.status,400,'a negative payment amount must be rejected');
 const partialPayment=await request(`/api/invoices/${payInvoice.data.id}/payments`,{cookie:first.cookie,method:'POST',body:JSON.stringify({amount:1000,method:'eft',reference:'EFT-1',paidDate:'2026-08-16'})});assert.equal(partialPayment.response.status,201);
 const afterPartial=await request('/api/bootstrap',{cookie:first.cookie}),partialInvoice=afterPartial.data.invoices.find(i=>i.id===payInvoice.data.id);assert.equal(partialInvoice.amountPaid,1000);assert.equal(partialInvoice.status,'draft','a partial payment must not mark the invoice fully paid');
 const finalPayment=await request(`/api/invoices/${payInvoice.data.id}/payments`,{cookie:first.cookie,method:'POST',body:JSON.stringify({amount:1185,paidDate:'2026-08-20'})});assert.equal(finalPayment.response.status,201,'total 1900*1.15=2185, so 1000+1185 must exactly settle the invoice');
 const afterFull=await request('/api/bootstrap',{cookie:first.cookie}),paidInvoice=afterFull.data.invoices.find(i=>i.id===payInvoice.data.id);assert.equal(paidInvoice.amountPaid,2185);assert.equal(paidInvoice.status,'paid','cumulative payments reaching the invoice total must auto-mark it paid');assert.equal(paidInvoice.paidDate,'2026-08-20');
 const notificationsAfterFullPayment=await request('/api/enterprise/summary',{cookie:first.cookie});assert.ok(notificationsAfterFullPayment.data.notifications.some(n=>n.title==='Invoice paid'&&n.message.includes('INV-PAY-0001')),'fully paying an invoice must notify the organization');
 const paymentsList=await request(`/api/invoices/${payInvoice.data.id}/payments`,{cookie:first.cookie});assert.equal(paymentsList.data.length,2);
 const otherOrgPaymentAttempt=await request(`/api/invoices/${payInvoice.data.id}/payments`,{cookie:second.cookie,method:'POST',body:JSON.stringify({amount:10})});assert.equal(otherOrgPaymentAttempt.response.status,404,'payments must be tenant-isolated');
 assert.equal((await request(`/api/payments/${paymentsList.data[0].id}`,{cookie:first.cookie,method:'DELETE'})).response.status,200,'paymentsList is ordered newest first, so this voids the 1185 payment');
 const afterVoid=await request('/api/bootstrap',{cookie:first.cookie}),revertedInvoice=afterVoid.data.invoices.find(i=>i.id===payInvoice.data.id);assert.equal(revertedInvoice.amountPaid,1000);assert.equal(revertedInvoice.status,'draft','voiding a payment that drops the balance below the total must revert the invoice out of paid status');

 const payExpense=await request('/api/expenses',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'BILL-PAY-0001',vendor:'Pay Co',category:'Software',date:'2026-08-15',due:'2026-08-20',amount:400,status:'due'})});assert.equal(payExpense.response.status,201);
 const expensePayment=await request(`/api/expenses/${payExpense.data.id}/payments`,{cookie:first.cookie,method:'POST',body:JSON.stringify({amount:400,paidDate:'2026-08-18'})});assert.equal(expensePayment.response.status,201);
 const afterExpensePaid=await request('/api/bootstrap',{cookie:first.cookie}),paidExpense=afterExpensePaid.data.expenses.find(e=>e.id===payExpense.data.id);assert.equal(paidExpense.status,'paid','a payment covering the full expense amount must auto-mark it paid');assert.equal(paidExpense.amountPaid,400);
 const notificationsAfterExpensePaid=await request('/api/enterprise/summary',{cookie:first.cookie});assert.ok(notificationsAfterExpensePaid.data.notifications.some(n=>n.title==='Expense paid'&&n.message.includes('BILL-PAY-0001')),'fully paying an expense must notify the organization');

 const ledgerAfterPayments=await request('/api/enterprise/summary',{cookie:first.cookie}),ledgerBalance=code=>ledgerAfterPayments.data.accounts.find(a=>a.code===code).balance;
 assert.equal(ledgerBalance('1100'),1185,'AR must reflect the payments-test invoice recognized (2185) less the surviving 1000 payment, with the voided 1185 payment excluded');
 assert.equal(ledgerBalance('4000'),1900,'Sales must recognize the invoice net of discount but excluding VAT, exactly once, regardless of how many payments were recorded or voided against it');
 assert.equal(ledgerBalance('2100'),285,'VAT payable must equal the 15% VAT on the recognized invoice');
 assert.equal(ledgerBalance('1000'),1000-400,'Bank must reflect the surviving 1000 invoice payment less the 400 expense payment');
 assert.equal(ledgerBalance('2000'),250,'Accounts payable must still carry the unpaid BILL-0001 accrual; the fully paid BILL-PAY-0001 accrual and settlement must net to zero');
 assert.equal(ledgerBalance('6000'),250+400,'Operating expenses must include both the unpaid and the paid expense at their full accrued amounts');
 assert.equal(ledgerAfterPayments.data.statements.accountingEquationDifference,0,'assets must equal liabilities+equity+netProfit after this mix of auto-posted invoice and expense journals');

 const badQuote=await request('/api/quotes',{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'QUO-0001',clientId:client.data.id,issue:'2026-08-20',expiry:'2026-08-10',items:[{description:'Advisory',qty:1,rate:5000}]})});assert.equal(badQuote.response.status,400,'expiry before issue must be rejected');
 const quote=await request('/api/quotes',{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'QUO-0001',clientId:client.data.id,issue:'2026-08-15',expiry:'2026-09-14',taxRate:15,discount:0,notes:'Thanks for considering us',items:[{description:'Advisory',qty:5,rate:1000,unit:'hours'}]})});assert.equal(quote.response.status,201);
 await assertPdf(await rawRequest(`/api/quotes/${quote.data.id}/pdf`,{cookie:first.cookie}));
 assert.equal((await request(`/api/quotes/${quote.data.id}`,{cookie:first.cookie,method:'PUT',body:JSON.stringify({number:'QUO-0001',clientId:client.data.id,issue:'2026-08-15',expiry:'2026-09-14',taxRate:15,discount:0,notes:'Updated scope',items:[{description:'Advisory updated',qty:6,rate:1000,unit:'hours'}]})})).response.status,200);
 const quoteBootstrap=await request('/api/bootstrap',{cookie:first.cookie});assert.equal(quoteBootstrap.data.quotes.length,1);assert.equal(quoteBootstrap.data.quotes[0].items[0].description,'Advisory updated');assert.equal(quoteBootstrap.data.quotes[0].items[0].unit,'hours');assert.equal(quoteBootstrap.data.quotes[0].status,'draft');
 assert.equal((await request(`/api/quotes/${quote.data.id}`,{cookie:first.cookie,method:'PATCH',body:JSON.stringify({status:'sent'})})).response.status,200);
 assert.equal((await request(`/api/quotes/${quote.data.id}`,{cookie:first.cookie,method:'PATCH',body:JSON.stringify({status:'accepted'})})).response.status,200);
 const converted=await request(`/api/quotes/${quote.data.id}/convert-to-invoice`,{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'INV-QUO-0001'})});assert.equal(converted.response.status,201);
 const convertedInvoice=(await request('/api/bootstrap',{cookie:first.cookie})).data.invoices.find(i=>i.number==='INV-QUO-0001');assert.ok(convertedInvoice);assert.equal(convertedInvoice.items[0].description,'Advisory updated');assert.equal(convertedInvoice.items[0].qty,6);
 const reconvert=await request(`/api/quotes/${quote.data.id}/convert-to-invoice`,{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'INV-QUO-0002'})});assert.equal(reconvert.response.status,409,'a quote already converted must not convert again');
 const secondQuote=await request('/api/quotes',{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'QUO-0002',clientId:client.data.id,issue:'2026-08-15',expiry:'2026-09-14',items:[{description:'Follow-up',qty:1,rate:500}]})});assert.equal(secondQuote.response.status,201);assert.equal((await request(`/api/quotes/${secondQuote.data.id}`,{cookie:first.cookie,method:'DELETE'})).response.status,200);assert.equal((await request('/api/bootstrap',{cookie:first.cookie})).data.quotes.length,1,'deleted quote must not remain');
 assert.equal((await request(`/api/clients/${client.data.id}`,{cookie:first.cookie,method:'PUT',body:JSON.stringify({name:'Client One Updated',email:'client@example.com',address:'Johannesburg',vatNumber:'4123456789'})})).response.status,200);
 assert.equal((await request(`/api/invoices/${invoice.data.id}`,{cookie:first.cookie,method:'PUT',body:JSON.stringify({number:'INV-0001',clientId:client.data.id,issue:'2026-08-15',due:'2026-08-30',taxRate:15,discount:0,notes:'Updated',paymentDetails:'EFT',items:[{description:'Design updated',qty:1,rate:2200,unit:'hours'}]})})).response.status,200);
 assert.equal((await request(`/api/expenses/${expense.data.id}`,{cookie:first.cookie,method:'PUT',body:JSON.stringify({reference:'BILL-0001',vendor:'Cloud Co',category:'Software',date:'2026-08-15',due:'2026-08-20',amount:300,status:'paid',notes:'Updated hosting'})})).response.status,200);
 const firstData=await request('/api/bootstrap',{cookie:first.cookie});assert.equal(firstData.data.clients.length,1);assert.equal(firstData.data.clients[0].name,'Client One Updated');assert.equal(firstData.data.invoices.length,3,'original invoice, the payments-test invoice, and the one converted from the accepted quote');const originalInvoice=firstData.data.invoices.find(i=>i.number==='INV-0001');assert.equal(originalInvoice.taxRate,15);assert.equal(originalInvoice.items[0].description,'Design updated');assert.equal(originalInvoice.items[0].unit,'hours');assert.equal(firstData.data.expenses.length,2,'the original expense plus the payments-test expense');const originalExpense=firstData.data.expenses.find(e=>e.reference==='BILL-0001');assert.equal(originalExpense.amount,300);
 const isolated=await request('/api/bootstrap',{cookie:second.cookie});assert.equal(isolated.data.clients.length,0);assert.equal(isolated.data.invoices.length,0);assert.equal(isolated.data.quotes.length,0);assert.equal(isolated.data.expenses.length,0);
 const clientsCsv='name,email,address,vatNumber\nImported Co,imported@example.com,"1 Long St, Cape Town",4987654321\n,missing-name@example.com,,\n';
 const clientsImport=await request('/api/enterprise/import/clients',{cookie:first.cookie,method:'POST',body:JSON.stringify({csv:clientsCsv})});assert.equal(clientsImport.response.status,201);assert.equal(clientsImport.data.imported,1);assert.equal(clientsImport.data.skipped,1);assert.equal(clientsImport.data.errors[0].row,3);
 const expensesCsv='reference,vendor,category,date,due,amount,status,notes\nBILL-0002,Office Supplies Co,Office,2026-08-16,2026-08-25,120,due,Stationery\nBILL-0001,Cloud Co,Software,2026-08-15,2026-08-20,999,due,Duplicate reference\n';
 const expensesImport=await request('/api/enterprise/import/expenses',{cookie:first.cookie,method:'POST',body:JSON.stringify({csv:expensesCsv})});assert.equal(expensesImport.response.status,201);assert.equal(expensesImport.data.imported,1);assert.equal(expensesImport.data.skipped,1);assert.match(expensesImport.data.errors[0].reason,/Duplicate reference/);
 const invoicesCsv='number,clientEmail,issueDate,dueDate,taxRate,discount,notes,paymentDetails,itemDescription,itemQty,itemUnit,itemRate\nINV-9001,newclient@example.com,2026-08-16,2026-08-30,15,0,Imported,EFT,Consulting,3,hours,900\nINV-9001,newclient@example.com,2026-08-16,2026-08-30,15,0,Imported,EFT,Travel,1,trip,500\n';
 const invoicesImport=await request('/api/enterprise/import/invoices',{cookie:first.cookie,method:'POST',body:JSON.stringify({csv:invoicesCsv})});assert.equal(invoicesImport.response.status,201);assert.equal(invoicesImport.data.imported,1);assert.equal(invoicesImport.data.skipped,0);assert.match(invoicesImport.data.errors[0].reason,/created a new client/);
 const afterImport=await request('/api/bootstrap',{cookie:first.cookie});assert.equal(afterImport.data.clients.length,3,'original + imported + auto-created client');assert.equal(afterImport.data.expenses.length,3,'original + payments-test + imported expense');const importedInvoice=afterImport.data.invoices.find(i=>i.number==='INV-9001');assert.ok(importedInvoice);assert.equal(importedInvoice.items.length,2);assert.equal(importedInvoice.items[0].unit,'hours');
 const note=await request('/api/enterprise/notes',{cookie:first.cookie,method:'POST',body:JSON.stringify({title:'Landlord call',body:'Renewed the office lease for another year'})});assert.equal(note.response.status,201);
 assert.equal((await request(`/api/enterprise/notes/${note.data.id}`,{cookie:first.cookie,method:'PUT',body:JSON.stringify({title:'Landlord call',body:'Updated: renewed for two years'})})).response.status,200);
 const notesAfterUpdate=await request('/api/enterprise/summary',{cookie:first.cookie});assert.equal(notesAfterUpdate.data.notes.length,1);assert.match(notesAfterUpdate.data.notes[0].body,/two years/);
 const isolatedNotes=await request('/api/enterprise/summary',{cookie:second.cookie});assert.equal(isolatedNotes.data.notes.length,0,'notes must be scoped to the organization');
 assert.equal((await request(`/api/enterprise/notes/${note.data.id}`,{cookie:first.cookie,method:'DELETE'})).response.status,200);assert.equal((await request('/api/enterprise/summary',{cookie:first.cookie})).data.notes.length,0);
 const budget=await request('/api/enterprise/budgets',{cookie:first.cookie,method:'POST',body:JSON.stringify({category:'Software',periodType:'monthly',periodStart:'2026-08-01',amount:500})});assert.equal(budget.response.status,201);
 const duplicateBudget=await request('/api/enterprise/budgets',{cookie:first.cookie,method:'POST',body:JSON.stringify({category:'Software',periodType:'monthly',periodStart:'2026-08-01',amount:999})});assert.equal(duplicateBudget.response.status,409,'a duplicate category/period/start budget must be rejected');
 const invalidPeriodBudget=await request('/api/enterprise/budgets',{cookie:first.cookie,method:'POST',body:JSON.stringify({category:'Rent',periodType:'weekly',periodStart:'2026-08-01',amount:100})});assert.equal(invalidPeriodBudget.response.status,400,'only monthly, quarterly or yearly periods are valid');
 const budgetsAfterCreate=await request('/api/enterprise/summary',{cookie:first.cookie});assert.equal(budgetsAfterCreate.data.budgets.length,1);assert.equal(budgetsAfterCreate.data.budgets[0].category,'Software');
 assert.equal((await request(`/api/enterprise/budgets/${budget.data.id}`,{cookie:first.cookie,method:'DELETE'})).response.status,200);assert.equal((await request('/api/enterprise/summary',{cookie:first.cookie})).data.budgets.length,0);
 const enterprise=await request('/api/enterprise/summary',{cookie:first.cookie});assert.equal(enterprise.data.role,'owner');assert.equal(enterprise.data.organizations.length,1);const primaryOrg=enterprise.data.activeOrganizationId;
 const newOrg=await request('/api/enterprise/organizations',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Acme Holdings',currency:'ZAR'})});assert.equal(newOrg.response.status,201);assert.equal((await request('/api/enterprise/organizations/switch',{cookie:first.cookie,method:'POST',body:JSON.stringify({organizationId:newOrg.data.id})})).response.status,200);const holdingData=await request('/api/bootstrap',{cookie:first.cookie});assert.equal(holdingData.data.clients.length,0);const holdingClient=await request('/api/clients',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Holding Client',email:'holding@example.com'})});assert.equal(holdingClient.response.status,201);const duplicateNumberDifferentOrg=await request('/api/invoices',{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'INV-0001',clientId:holdingClient.data.id,issue:'2026-08-15',due:'2026-08-30',taxRate:0,discount:0,items:[{description:'Advisory',qty:1,rate:5000}]})});assert.equal(duplicateNumberDifferentOrg.response.status,201);assert.equal((await request('/api/enterprise/organizations/switch',{cookie:first.cookie,method:'POST',body:JSON.stringify({organizationId:primaryOrg})})).response.status,200);
 const invitation=await request('/api/enterprise/invitations',{cookie:first.cookie,method:'POST',body:JSON.stringify({email:'other@example.net',role:'approver'})});assert.equal(invitation.response.status,201);assert.ok(invitation.data.inviteToken);assert.equal((await request('/api/enterprise/invitations/accept',{cookie:second.cookie,method:'POST',body:JSON.stringify({token:invitation.data.inviteToken})})).response.status,200);const invitedSummary=await request('/api/enterprise/summary',{cookie:second.cookie});assert.equal(invitedSummary.data.role,'approver');const forbidden=await request('/api/clients',{cookie:second.cookie,method:'POST',body:JSON.stringify({name:'Forbidden'})});assert.equal(forbidden.response.status,403);
 const rule=await request('/api/enterprise/approval-rules',{cookie:first.cookie,method:'POST',body:JSON.stringify({entityType:'invoice',minAmount:1000,requiredApprovals:1})});assert.equal(rule.response.status,201);const approval=await request('/api/enterprise/approvals',{cookie:first.cookie,method:'POST',body:JSON.stringify({entityType:'invoice',entityId:String(invoice.data.id),amount:2200})});assert.equal(approval.response.status,201);assert.equal(approval.data.requiredApprovals,1);assert.equal((await request(`/api/enterprise/approvals/${approval.data.id}`,{cookie:first.cookie,method:'PATCH',body:JSON.stringify({status:'approved'})})).response.status,403);assert.equal((await request(`/api/enterprise/approvals/${approval.data.id}`,{cookie:second.cookie,method:'PATCH',body:JSON.stringify({status:'approved',note:'Within budget'})})).response.status,200);
 const teamSummary=await request('/api/enterprise/summary',{cookie:first.cookie}),ownerMember=teamSummary.data.members.find(m=>m.role==='owner'),secondMember=teamSummary.data.members.find(m=>m.email==='other@example.net');assert.ok(ownerMember&&secondMember);
 assert.equal((await request(`/api/enterprise/members/${secondMember.id}`,{cookie:second.cookie,method:'DELETE'})).response.status,403,'a role without manage_team cannot remove members');
 assert.equal((await request(`/api/enterprise/members/${ownerMember.id}`,{cookie:first.cookie,method:'DELETE'})).response.status,400,'a member cannot remove themselves');
 assert.equal((await request(`/api/enterprise/members/${secondMember.id}`,{cookie:first.cookie,method:'DELETE'})).response.status,200);
 assert.equal((await request('/api/enterprise/summary',{cookie:second.cookie})).response.status,401,'a removed member loses organization access entirely');
 assert.equal((await request('/api/enterprise/summary',{cookie:first.cookie})).data.members.length,1,'removed member no longer appears in the team list');
 const accounting=await request('/api/enterprise/summary',{cookie:first.cookie}),bankLedger=accounting.data.accounts.find(a=>a.code==='1000'),salesLedger=accounting.data.accounts.find(a=>a.code==='4000');assert.ok(bankLedger&&salesLedger);assert.equal(accounting.data.statements.accountingEquationDifference,0,'invoice/expense auto-posted journals must already balance before any manual journal is added');const before=accounting.data.statements;const journal=await request('/api/enterprise/journals',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'JNL-0001',entryDate:'2026-08-15',memo:'Opening sale',lines:[{accountId:bankLedger.id,debit:1000},{accountId:salesLedger.id,credit:1000}]})});assert.equal(journal.response.status,201);const unbalanced=await request('/api/enterprise/journals',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'JNL-BAD',entryDate:'2026-08-15',lines:[{accountId:bankLedger.id,debit:1000},{accountId:salesLedger.id,credit:900}]})});assert.equal(unbalanced.response.status,400);const statements=await request('/api/enterprise/summary',{cookie:first.cookie});assert.equal(statements.data.statements.revenue-before.revenue,1000,'posting the manual journal must increase revenue by exactly its credit amount, on top of whatever invoice auto-posting already recognized');assert.equal(statements.data.statements.assets-before.assets,1000,'posting the manual journal must increase assets by exactly its debit amount');assert.equal(statements.data.statements.accountingEquationDifference,0,'the accounting equation must still balance after mixing manual and auto-posted journals');assert.equal((await request('/api/enterprise/accounting-periods/lock',{cookie:first.cookie,method:'POST',body:JSON.stringify({startDate:'2026-08-01',endDate:'2026-08-31'})})).response.status,201);assert.equal((await request('/api/enterprise/journals',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'JNL-LOCKED',entryDate:'2026-08-20',lines:[{accountId:bankLedger.id,debit:10},{accountId:salesLedger.id,credit:10}]})})).response.status,409);
 const connection=await request('/api/enterprise/connections',{cookie:first.cookie,method:'POST',body:JSON.stringify({category:'accounting',provider:'xero',displayName:'Xero Production'})});assert.equal(connection.response.status,201);assert.equal((await request(`/api/enterprise/connections/${connection.data.id}`,{cookie:first.cookie,method:'PATCH',body:JSON.stringify({credentials:{accessToken:'test-token',tenantId:'xero-tenant'}})})).response.status,200);assert.equal((await request(`/api/enterprise/connections/${connection.data.id}/sync`,{cookie:first.cookie,method:'POST',body:'{}'})).response.status,202);
 const bank=await request('/api/enterprise/bank-accounts',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Operating account',accountNumberMasked:'••••1234',currency:'ZAR',balance:10000})});assert.equal(bank.response.status,201);const imported=await request('/api/enterprise/bank-transactions/import',{cookie:first.cookie,method:'POST',body:JSON.stringify({bankAccountId:bank.data.id,transactions:[{externalId:'bank-1',date:'2026-08-15',description:'Client payment',amount:2200,currency:'ZAR'}]})});assert.equal(imported.data.imported,1);const bankSummary=await request('/api/enterprise/summary',{cookie:first.cookie});const transaction=bankSummary.data.bankTransactions[0];assert.equal((await request(`/api/enterprise/bank-transactions/${transaction.id}/match`,{cookie:first.cookie,method:'POST',body:JSON.stringify({matchedType:'invoice',matchedId:String(invoice.data.id)})})).response.status,200);

 const suggestionImport=await request('/api/enterprise/bank-transactions/import',{cookie:first.cookie,method:'POST',body:JSON.stringify({bankAccountId:bank.data.id,transactions:[{externalId:'suggest-1',date:'2026-08-29',description:'Payment ref INV-PAY-0001',amount:1185,currency:'ZAR'}]})});assert.equal(suggestionImport.data.imported,1,'payInvoice is still draft with a 1185 outstanding balance (2185 total less the surviving 1000 payment), close to its 2026-08-30 due date');
 const suggestionSummary=await request('/api/enterprise/summary',{cookie:first.cookie}),suggestionTx=suggestionSummary.data.bankTransactions.find(t=>t.description.includes('INV-PAY-0001'));assert.ok(suggestionTx);
 const suggestions=await request(`/api/enterprise/bank-transactions/${suggestionTx.id}/suggestions`,{cookie:first.cookie});assert.equal(suggestions.response.status,200);assert.ok(suggestions.data.suggestions.length>0,'a transaction whose amount and description closely match an outstanding invoice must produce at least one suggestion');
 const topSuggestion=suggestions.data.suggestions[0];assert.equal(topSuggestion.type,'invoice');assert.equal(topSuggestion.label,'INV-PAY-0001');assert.equal(topSuggestion.outstanding,1185);assert.ok(topSuggestion.confidence>=90,`expected a high-confidence match for an exact amount+description+near-due-date hit, got ${topSuggestion.confidence}`);
 assert.equal((await request(`/api/enterprise/bank-transactions/${suggestionTx.id}/match`,{cookie:first.cookie,method:'POST',body:JSON.stringify({matchedType:topSuggestion.type,matchedId:topSuggestion.id})})).response.status,200,'the suggested match must be a real, matchable invoice id');
 const noSuggestionImport=await request('/api/enterprise/bank-transactions/import',{cookie:first.cookie,method:'POST',body:JSON.stringify({bankAccountId:bank.data.id,transactions:[{externalId:'suggest-none',date:'2026-08-15',description:'Unrelated ATM withdrawal',amount:-99999,currency:'ZAR'}]})});assert.equal(noSuggestionImport.data.imported,1);
 const noSuggestionSummary=await request('/api/enterprise/summary',{cookie:first.cookie}),noSuggestionTx=noSuggestionSummary.data.bankTransactions.find(t=>t.description==='Unrelated ATM withdrawal');const noSuggestions=await request(`/api/enterprise/bank-transactions/${noSuggestionTx.id}/suggestions`,{cookie:first.cookie});assert.equal(noSuggestions.response.status,200);assert.equal(noSuggestions.data.suggestions.length,0,'a transaction that matches nothing on amount, date or description must yield no suggestions rather than noisy guesses');
 const document=await request('/api/enterprise/documents',{cookie:first.cookie,method:'POST',body:JSON.stringify({type:'purchase_order',number:'PO-0001',counterparty:'Supplier',issueDate:'2026-08-15',status:'draft',total:3000,currency:'ZAR',payload:{items:[]}})});assert.equal(document.response.status,201);const payroll=await request('/api/enterprise/payroll-runs',{cookie:first.cookie,method:'POST',body:JSON.stringify({provider:'PaySpace',periodStart:'2026-08-01',periodEnd:'2026-08-31',gross:100000,tax:20000,net:80000,employeeCount:4,status:'draft'})});assert.equal(payroll.response.status,201);
 const uploaded=await request('/api/enterprise/files',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'receipt.txt',entityType:'expense',entityId:String(expense.data.id),data:'data:text/plain;base64,aGVsbG8=',documentCategory:'statutory'})});assert.equal(uploaded.response.status,201);const recurring=await request('/api/enterprise/recurring',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Monthly hosting',frequency:'monthly',nextRunDate:'2027-01-01',templateType:'expense',payload:{vendor:'Cloud Co',category:'Software',amount:500}})});assert.equal(recurring.response.status,201);
 const generalDoc=await request('/api/enterprise/files',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'lease.pdf',entityType:'general',data:'data:application/pdf;base64,aGVsbG8=',documentCategory:'statutory'})});assert.equal(generalDoc.response.status,201);
 const badCategory=await request('/api/enterprise/files',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'bad.pdf',entityType:'general',data:'data:application/pdf;base64,aGVsbG8=',documentCategory:'not-a-real-category'})});assert.equal(badCategory.response.status,400,'an invalid document category on a general file must be rejected');
 const filesSummary=await request('/api/enterprise/summary',{cookie:first.cookie});const expenseFile=filesSummary.data.files.find(f=>f.id===uploaded.data.id),generalFile=filesSummary.data.files.find(f=>f.id===generalDoc.data.id);assert.equal(expenseFile.documentCategory,'','a category sent for a non-general file must be ignored, not stored');assert.equal(generalFile.documentCategory,'statutory');

 const contextualNote=await request('/api/enterprise/notes',{cookie:first.cookie,method:'POST',body:JSON.stringify({title:'Follow up',body:'Call before due date',entityType:'invoice',entityId:String(invoice.data.id)})});assert.equal(contextualNote.response.status,201);
 const generalNote=await request('/api/enterprise/notes',{cookie:first.cookie,method:'POST',body:JSON.stringify({title:'General note',body:'Not tied to any record'})});assert.equal(generalNote.response.status,201);
 const notesSummary=await request('/api/enterprise/summary',{cookie:first.cookie});const invoiceNote=notesSummary.data.notes.find(n=>n.id===contextualNote.data.id),untaggedNote=notesSummary.data.notes.find(n=>n.id===generalNote.data.id);assert.equal(invoiceNote.entityType,'invoice');assert.equal(invoiceNote.entityId,String(invoice.data.id));assert.equal(untaggedNote.entityType,'','a note posted without entityType must default to general/untagged, not null or undefined');

 const clientFile=await request('/api/enterprise/files',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'contract.pdf',entityType:'client',entityId:String(client.data.id),data:'data:application/pdf;base64,aGVsbG8='})});assert.equal(clientFile.response.status,201,'entityType "client" must round-trip with no backend change, since stored_files.entity_type is unconstrained');
 const clientFileSummary=(await request('/api/enterprise/summary',{cookie:first.cookie})).data.files.find(f=>f.id===clientFile.data.id);assert.equal(clientFileSummary.entityType,'client');assert.equal(clientFileSummary.entityId,String(client.data.id));

 const recurringInvoiceTemplate=await request('/api/enterprise/recurring',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Monthly retainer',frequency:'monthly',nextRunDate:'2027-02-01',templateType:'invoice',payload:{clientId:client.data.id,prefix:'RET',dueDays:14,taxRate:15,discount:0,notes:'Retainer',paymentDetails:'EFT',items:[{description:'Retainer',qty:1,rate:1000,unit:''}]}})});assert.equal(recurringInvoiceTemplate.response.status,201,'a structured object payload (not a JSON string) must be accepted for invoice recurring templates too');
 const apiKey=await request('/api/enterprise/api-keys',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Reporting integration',scopes:['read']})});assert.equal(apiKey.response.status,201);const apiAccess=await request('/api/bootstrap',{headers:{Authorization:`Bearer ${apiKey.data.key}`}});assert.equal(apiAccess.response.status,200);assert.equal(apiAccess.data.profile.companyName,'Acme Studio');
 const writeKey=await request('/api/enterprise/api-keys',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Automation integration',scopes:['read','write']})});const idempotentHeaders={Authorization:`Bearer ${writeKey.data.key}`,'Idempotency-Key':'create-client-001'},automatedClient=await request('/api/clients',{method:'POST',headers:idempotentHeaders,body:JSON.stringify({name:'API Client'})}),replayedClient=await request('/api/clients',{method:'POST',headers:idempotentHeaders,body:JSON.stringify({name:'API Client'})});assert.equal(automatedClient.response.status,201);assert.equal(replayedClient.data.id,automatedClient.data.id);assert.equal(replayedClient.response.headers.get('idempotent-replayed'),'true');
 const audit=await request('/api/enterprise/audit',{cookie:first.cookie});assert.equal(audit.response.status,200);assert.ok(audit.data.audit.length>=10);
 const exported=await request('/api/account/export',{cookie:first.cookie});assert.equal(exported.data.profile.companyName,'Acme Studio');assert.equal(exported.data.invoices.find(i=>i.number==='INV-0001').items[0].description,'Design updated');
 const readiness=await request('/api/enterprise/readiness',{cookie:first.cookie});assert.equal(readiness.response.status,200);assert.equal(readiness.data.ready,false);

 await assertPdf(await rawRequest(`/api/enterprise/documents/${document.data.id}/pdf`,{cookie:first.cookie}));
 const emptyDocument=await request('/api/enterprise/documents',{cookie:first.cookie,method:'POST',body:JSON.stringify({type:'credit_note',number:'CN-0001',counterparty:'Refund Co',issueDate:'2026-08-15',total:0,currency:'ZAR'})});assert.equal(emptyDocument.response.status,201,'business documents with no payload at all must still be creatable');
 await assertPdf(await rawRequest(`/api/enterprise/documents/${emptyDocument.data.id}/pdf`,{cookie:first.cookie}));

 const svgLogo='data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"></svg>').toString('base64');
 assert.equal((await request('/api/profile',{cookie:first.cookie,method:'PUT',body:JSON.stringify({companyName:'Acme Studio',ownerName:'Ada Owner',email:'owner@example.com',currency:'ZAR',logo:svgLogo})})).response.status,200);
 await assertPdf(await rawRequest(`/api/invoices/${invoice.data.id}/pdf`,{cookie:first.cookie})); // an unsupported (SVG) logo must fall back gracefully instead of crashing PDF generation
 const mfaSetup=await request('/api/security/mfa/setup',{cookie:first.cookie,method:'POST',body:'{}'});assert.equal(mfaSetup.response.status,200);assert.equal((await request('/api/security/mfa/enable',{cookie:first.cookie,method:'POST',body:JSON.stringify({code:totp(mfaSetup.data.secret)})})).response.status,200);
 const logout=await request('/api/auth/logout',{cookie:first.cookie,method:'POST',body:'{}'});assert.equal(logout.response.status,200);const denied=await request('/api/bootstrap',{cookie:first.cookie});assert.equal(denied.response.status,401);assert.equal((await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'A-secure-password9'})})).response.status,401);const mfaLogin=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'A-secure-password9',mfaCode:totp(mfaSetup.data.secret)})});assert.equal(mfaLogin.response.status,200);
 const reset=await request('/api/auth/password/request',{method:'POST',body:JSON.stringify({email:'owner@example.com'})});assert.ok(reset.data.resetToken);assert.equal((await request('/api/auth/password/reset',{method:'POST',body:JSON.stringify({token:reset.data.resetToken,password:'A-new-secure-password9'})})).response.status,200);assert.equal((await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'A-new-secure-password9',mfaCode:totp(mfaSetup.data.secret)})})).response.status,200);
}

test('core bookkeeping and enterprise governance flow on SQLite',t=>coreFlow(t));
if(process.env.TEST_DATABASE_URL)test('core bookkeeping and enterprise governance flow on PostgreSQL',t=>coreFlow(t,process.env.TEST_DATABASE_URL));
