const test = require('node:test');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const {once} = require('node:events');
const {totp} = require('../security');
const {assertSafeOutboundUrl,privateAddress} = require('../network-security');
const {encryptBackup,decryptBackup} = require('../operations');

test('outbound URL policy blocks local and private networks',async()=>{
 assert.equal(privateAddress('127.0.0.1'),true);
 assert.equal(privateAddress('10.20.30.40'),true);
 assert.equal(privateAddress('169.254.169.254'),true);
 assert.equal(privateAddress('8.8.8.8'),false);
 await assert.rejects(()=>assertSafeOutboundUrl('http://127.0.0.1/admin'),/HTTPS/);
 await assert.rejects(()=>assertSafeOutboundUrl('https://127.0.0.1/admin'),/Private network/);
});

test('offsite backup encryption round trips and rejects the wrong key',()=>{
 const previous=process.env.BACKUP_ENCRYPTION_KEY;process.env.BACKUP_ENCRYPTION_KEY='test-backup-key-that-is-longer-than-32-characters';
 try{const source=Buffer.from('sqlite backup bytes'),encrypted=encryptBackup(source);assert.notDeepEqual(encrypted,source);assert.deepEqual(decryptBackup(encrypted),source);process.env.BACKUP_ENCRYPTION_KEY='different-backup-key-that-is-long-enough';assert.throws(()=>decryptBackup(encrypted));}finally{if(previous===undefined)delete process.env.BACKUP_ENCRYPTION_KEY;else process.env.BACKUP_ENCRYPTION_KEY=previous}
});

test('required email verification blocks financial mutations',async t=>{
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'ledgeriq-verify-test-')),port=34000+Math.floor(Math.random()*1000),origin=`http://localhost:${port}`;
 const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,NODE_ENV:'development',PORT:String(port),APP_ORIGIN:origin,REQUIRE_EMAIL_VERIFICATION:'true',SESSION_SECRET:'verification-test-secret-longer-than-32-characters',INTEGRATION_ENCRYPTION_KEY:'verification-integration-key-longer-than-32-characters',LEDGERIQ_DATA_DIR:path.join(temp,'data'),LEDGERIQ_BACKUP_DIR:path.join(temp,'backups'),OBJECT_STORAGE_PATH:path.join(temp,'documents')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',data=>process.stderr.write(data));t.after(async()=>{child.kill();await once(child,'exit');fs.rmSync(temp,{recursive:true,force:true})});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('verification server start timeout')),5000);child.stdout.on('data',data=>{if(String(data).includes('ledgerIQ running')){clearTimeout(timer);resolve()}});child.on('exit',code=>reject(new Error(`verification server exited ${code}`)))});
 const response=await fetch(origin+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({email:'unverified@example.com',password:'a-secure-password',companyName:'Verify Co',ownerName:'Una Verified'})}),cookie=response.headers.get('set-cookie')?.split(';')[0];assert.equal(response.status,201);const registerData=await response.json();assert.ok(registerData.verificationToken);
 const blocked=await fetch(origin+'/api/clients',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie},body:JSON.stringify({name:'Blocked Client'})});assert.equal(blocked.status,403);assert.match((await blocked.json()).error,/Verify your email/);
 const unverifiedLogin=await fetch(origin+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({email:'unverified@example.com',password:'a-secure-password'})});assert.equal(unverifiedLogin.status,200,'login must never be blocked by unverified email');
 const resend=await fetch(origin+'/api/security/verify/resend',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie},body:'{}'});assert.equal(resend.status,200);const resendData=await resend.json();assert.ok(resendData.token);assert.notEqual(resendData.token,registerData.verificationToken);
 const staleToken=await fetch(origin+'/api/auth/verify-email',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({token:registerData.verificationToken})});assert.equal(staleToken.status,400,'a token invalidated by resend must not verify');
 const freshToken=await fetch(origin+'/api/auth/verify-email',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({token:resendData.token})});assert.equal(freshToken.status,200);
 const replayedToken=await fetch(origin+'/api/auth/verify-email',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({token:resendData.token})});assert.equal(replayedToken.status,400,'a used verification token must not be replayable');
});

async function coreFlow(t,databaseUrl=''){
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'ledgeriq-test-')),port=32000+Math.floor(Math.random()*2000);
 const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,NODE_ENV:'test',DATABASE_URL:databaseUrl,DATABASE_RESET_FOR_TESTS:databaseUrl?'true':'false',DISABLE_AUTOMATED_BACKUPS:databaseUrl?'true':'false',PORT:String(port),APP_ORIGIN:`http://localhost:${port}`,SESSION_SECRET:'test-secret-that-is-longer-than-32-characters',INTEGRATION_ENCRYPTION_KEY:'test-integration-secret-longer-than-32-characters',BILLING_WEBHOOK_SECRET:'test-billing-webhook-secret',LEDGERIQ_DATA_DIR:path.join(temp,'data'),LEDGERIQ_BACKUP_DIR:path.join(temp,'backups'),OBJECT_STORAGE_PATH:path.join(temp,'documents')},stdio:['ignore','pipe','pipe']});
 child.stderr.on('data',data=>process.stderr.write(data));
 t.after(async()=>{child.kill();await once(child,'exit');fs.rmSync(temp,{recursive:true,force:true})});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('server start timeout')),databaseUrl?15000:5000);child.stdout.on('data',data=>{if(String(data).includes('ledgerIQ running')){clearTimeout(timer);resolve()}});child.on('exit',code=>reject(new Error(`server exited ${code}`)))});
 const base=`http://localhost:${port}`;
 async function request(route,{cookie,...options}={}){const response=await fetch(base+route,{...options,headers:{'Content-Type':'application/json',Origin:base,...(cookie?{Cookie:cookie}:{}),...(options.headers||{})}}),data=await response.json();return{response,data,cookie:response.headers.get('set-cookie')?.split(';')[0]}}
 const landing=await fetch(base);assert.equal(landing.status,200);const landingHtml=await landing.text();assert.match(landingHtml,/ledgerIQ Business/);assert.match(landingHtml,/R5,990\/year/);assert.match(landingHtml,/R<\/span>10k/);assert.equal(landing.headers.get('x-frame-options'),'DENY');assert.equal((await fetch(base+'/developers')).status,200);
 for(const sensitive of ['/server.js','/enterprise.js','/package.json','/.env','/data/ledgeriq.sqlite','/backups/ledgeriq.sqlite'])assert.equal((await fetch(base+sensitive)).status,404,`${sensitive} must not be public`);
 const health=await request('/api/health');assert.equal(health.data.ok,true);const ready=await request('/api/ready');assert.equal(ready.response.status,200);assert.equal(ready.data.database,true);assert.equal((await request('/api/auth/register',{method:'POST',body:'{'})).response.status,400);
 const first=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'a-secure-password',companyName:'Acme Studio',ownerName:'Ada Owner'})});assert.equal(first.response.status,201);assert.match(first.cookie,/ledgeriq_session/);
 assert.ok(first.data.verificationToken);assert.equal((await request('/api/auth/verify-email',{method:'POST',body:JSON.stringify({token:first.data.verificationToken})})).response.status,200);const securityStatus=await request('/api/security/status',{cookie:first.cookie});assert.ok(securityStatus.data.emailVerifiedAt);
 const billingBody=JSON.stringify({email:'owner@example.com',status:'active'}),billingSignature=crypto.createHmac('sha256','test-billing-webhook-secret').update(billingBody).digest('hex'),billingOptions={method:'POST',headers:{'x-ledgeriq-signature':billingSignature},body:billingBody};const billed=await request('/api/billing/webhook',billingOptions);assert.equal(billed.response.status,200);assert.equal(billed.data.processed,true);const replayedBilling=await request('/api/billing/webhook',billingOptions);assert.equal(replayedBilling.data.replayed,true);
 const second=await request('/api/auth/register',{method:'POST',body:JSON.stringify({email:'other@example.com',password:'another-secure-password',companyName:'Other Co',ownerName:'Other Owner'})});assert.equal(second.response.status,201);
 const client=await request('/api/clients',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Client One',email:'client@example.com',address:'Cape Town',vatNumber:'4123456789'})});assert.equal(client.response.status,201);
 const invoice=await request('/api/invoices',{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'INV-0001',clientId:client.data.id,issue:'2026-08-15',due:'2026-08-30',taxRate:15,discount:100,notes:'Thanks',paymentDetails:'EFT',items:[{description:'Design',qty:2,rate:1000}]})});assert.equal(invoice.response.status,201);
 const expense=await request('/api/expenses',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'BILL-0001',vendor:'Cloud Co',category:'Software',date:'2026-08-15',due:'2026-08-20',amount:250,status:'due',notes:'Hosting'})});assert.equal(expense.response.status,201);
 assert.equal((await request(`/api/clients/${client.data.id}`,{cookie:first.cookie,method:'PUT',body:JSON.stringify({name:'Client One Updated',email:'client@example.com',address:'Johannesburg',vatNumber:'4123456789'})})).response.status,200);
 assert.equal((await request(`/api/invoices/${invoice.data.id}`,{cookie:first.cookie,method:'PUT',body:JSON.stringify({number:'INV-0001',clientId:client.data.id,issue:'2026-08-15',due:'2026-08-30',taxRate:15,discount:0,notes:'Updated',paymentDetails:'EFT',items:[{description:'Design updated',qty:1,rate:2200}]})})).response.status,200);
 assert.equal((await request(`/api/expenses/${expense.data.id}`,{cookie:first.cookie,method:'PUT',body:JSON.stringify({reference:'BILL-0001',vendor:'Cloud Co',category:'Software',date:'2026-08-15',due:'2026-08-20',amount:300,status:'paid',notes:'Updated hosting'})})).response.status,200);
 const firstData=await request('/api/bootstrap',{cookie:first.cookie});assert.equal(firstData.data.clients.length,1);assert.equal(firstData.data.clients[0].name,'Client One Updated');assert.equal(firstData.data.invoices.length,1);assert.equal(firstData.data.invoices[0].taxRate,15);assert.equal(firstData.data.invoices[0].items[0].description,'Design updated');assert.equal(firstData.data.expenses.length,1);assert.equal(firstData.data.expenses[0].amount,300);
 const isolated=await request('/api/bootstrap',{cookie:second.cookie});assert.equal(isolated.data.clients.length,0);assert.equal(isolated.data.invoices.length,0);assert.equal(isolated.data.expenses.length,0);
 const enterprise=await request('/api/enterprise/summary',{cookie:first.cookie});assert.equal(enterprise.data.role,'owner');assert.equal(enterprise.data.organizations.length,1);const primaryOrg=enterprise.data.activeOrganizationId;
 const newOrg=await request('/api/enterprise/organizations',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Acme Holdings',currency:'ZAR'})});assert.equal(newOrg.response.status,201);assert.equal((await request('/api/enterprise/organizations/switch',{cookie:first.cookie,method:'POST',body:JSON.stringify({organizationId:newOrg.data.id})})).response.status,200);const holdingData=await request('/api/bootstrap',{cookie:first.cookie});assert.equal(holdingData.data.clients.length,0);const holdingClient=await request('/api/clients',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Holding Client',email:'holding@example.com'})});assert.equal(holdingClient.response.status,201);const duplicateNumberDifferentOrg=await request('/api/invoices',{cookie:first.cookie,method:'POST',body:JSON.stringify({number:'INV-0001',clientId:holdingClient.data.id,issue:'2026-08-15',due:'2026-08-30',taxRate:0,discount:0,items:[{description:'Advisory',qty:1,rate:5000}]})});assert.equal(duplicateNumberDifferentOrg.response.status,201);assert.equal((await request('/api/enterprise/organizations/switch',{cookie:first.cookie,method:'POST',body:JSON.stringify({organizationId:primaryOrg})})).response.status,200);
 const invitation=await request('/api/enterprise/invitations',{cookie:first.cookie,method:'POST',body:JSON.stringify({email:'other@example.com',role:'approver'})});assert.equal(invitation.response.status,201);assert.ok(invitation.data.inviteToken);assert.equal((await request('/api/enterprise/invitations/accept',{cookie:second.cookie,method:'POST',body:JSON.stringify({token:invitation.data.inviteToken})})).response.status,200);const invitedSummary=await request('/api/enterprise/summary',{cookie:second.cookie});assert.equal(invitedSummary.data.role,'approver');const forbidden=await request('/api/clients',{cookie:second.cookie,method:'POST',body:JSON.stringify({name:'Forbidden'})});assert.equal(forbidden.response.status,403);
 const rule=await request('/api/enterprise/approval-rules',{cookie:first.cookie,method:'POST',body:JSON.stringify({entityType:'invoice',minAmount:1000,requiredApprovals:1})});assert.equal(rule.response.status,201);const approval=await request('/api/enterprise/approvals',{cookie:first.cookie,method:'POST',body:JSON.stringify({entityType:'invoice',entityId:String(invoice.data.id),amount:2200})});assert.equal(approval.response.status,201);assert.equal(approval.data.requiredApprovals,1);assert.equal((await request(`/api/enterprise/approvals/${approval.data.id}`,{cookie:first.cookie,method:'PATCH',body:JSON.stringify({status:'approved'})})).response.status,403);assert.equal((await request(`/api/enterprise/approvals/${approval.data.id}`,{cookie:second.cookie,method:'PATCH',body:JSON.stringify({status:'approved',note:'Within budget'})})).response.status,200);
 const teamSummary=await request('/api/enterprise/summary',{cookie:first.cookie}),ownerMember=teamSummary.data.members.find(m=>m.role==='owner'),secondMember=teamSummary.data.members.find(m=>m.email==='other@example.com');assert.ok(ownerMember&&secondMember);
 assert.equal((await request(`/api/enterprise/members/${secondMember.id}`,{cookie:second.cookie,method:'DELETE'})).response.status,403,'a role without manage_team cannot remove members');
 assert.equal((await request(`/api/enterprise/members/${ownerMember.id}`,{cookie:first.cookie,method:'DELETE'})).response.status,400,'a member cannot remove themselves');
 assert.equal((await request(`/api/enterprise/members/${secondMember.id}`,{cookie:first.cookie,method:'DELETE'})).response.status,200);
 assert.equal((await request('/api/enterprise/summary',{cookie:second.cookie})).response.status,401,'a removed member loses organization access entirely');
 assert.equal((await request('/api/enterprise/summary',{cookie:first.cookie})).data.members.length,1,'removed member no longer appears in the team list');
 const accounting=await request('/api/enterprise/summary',{cookie:first.cookie}),bankLedger=accounting.data.accounts.find(a=>a.code==='1000'),salesLedger=accounting.data.accounts.find(a=>a.code==='4000');assert.ok(bankLedger&&salesLedger);const journal=await request('/api/enterprise/journals',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'JNL-0001',entryDate:'2026-08-15',memo:'Opening sale',lines:[{accountId:bankLedger.id,debit:1000},{accountId:salesLedger.id,credit:1000}]})});assert.equal(journal.response.status,201);const unbalanced=await request('/api/enterprise/journals',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'JNL-BAD',entryDate:'2026-08-15',lines:[{accountId:bankLedger.id,debit:1000},{accountId:salesLedger.id,credit:900}]})});assert.equal(unbalanced.response.status,400);const statements=await request('/api/enterprise/summary',{cookie:first.cookie});assert.equal(statements.data.statements.revenue,1000);assert.equal(statements.data.statements.assets,1000);assert.equal(statements.data.statements.accountingEquationDifference,0);assert.equal((await request('/api/enterprise/accounting-periods/lock',{cookie:first.cookie,method:'POST',body:JSON.stringify({startDate:'2026-08-01',endDate:'2026-08-31'})})).response.status,201);assert.equal((await request('/api/enterprise/journals',{cookie:first.cookie,method:'POST',body:JSON.stringify({reference:'JNL-LOCKED',entryDate:'2026-08-20',lines:[{accountId:bankLedger.id,debit:10},{accountId:salesLedger.id,credit:10}]})})).response.status,409);
 const connection=await request('/api/enterprise/connections',{cookie:first.cookie,method:'POST',body:JSON.stringify({category:'accounting',provider:'xero',displayName:'Xero Production'})});assert.equal(connection.response.status,201);assert.equal((await request(`/api/enterprise/connections/${connection.data.id}`,{cookie:first.cookie,method:'PATCH',body:JSON.stringify({credentials:{accessToken:'test-token',tenantId:'xero-tenant'}})})).response.status,200);assert.equal((await request(`/api/enterprise/connections/${connection.data.id}/sync`,{cookie:first.cookie,method:'POST',body:'{}'})).response.status,202);
 const bank=await request('/api/enterprise/bank-accounts',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Operating account',accountNumberMasked:'••••1234',currency:'ZAR',balance:10000})});assert.equal(bank.response.status,201);const imported=await request('/api/enterprise/bank-transactions/import',{cookie:first.cookie,method:'POST',body:JSON.stringify({bankAccountId:bank.data.id,transactions:[{externalId:'bank-1',date:'2026-08-15',description:'Client payment',amount:2200,currency:'ZAR'}]})});assert.equal(imported.data.imported,1);const bankSummary=await request('/api/enterprise/summary',{cookie:first.cookie});const transaction=bankSummary.data.bankTransactions[0];assert.equal((await request(`/api/enterprise/bank-transactions/${transaction.id}/match`,{cookie:first.cookie,method:'POST',body:JSON.stringify({matchedType:'invoice',matchedId:String(invoice.data.id)})})).response.status,200);
 const document=await request('/api/enterprise/documents',{cookie:first.cookie,method:'POST',body:JSON.stringify({type:'purchase_order',number:'PO-0001',counterparty:'Supplier',issueDate:'2026-08-15',status:'draft',total:3000,currency:'ZAR',payload:{items:[]}})});assert.equal(document.response.status,201);const payroll=await request('/api/enterprise/payroll-runs',{cookie:first.cookie,method:'POST',body:JSON.stringify({provider:'PaySpace',periodStart:'2026-08-01',periodEnd:'2026-08-31',gross:100000,tax:20000,net:80000,employeeCount:4,status:'draft'})});assert.equal(payroll.response.status,201);
 const uploaded=await request('/api/enterprise/files',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'receipt.txt',entityType:'expense',entityId:String(expense.data.id),data:'data:text/plain;base64,aGVsbG8='})});assert.equal(uploaded.response.status,201);const recurring=await request('/api/enterprise/recurring',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Monthly hosting',frequency:'monthly',nextRunDate:'2027-01-01',templateType:'expense',payload:{vendor:'Cloud Co',category:'Software',amount:500}})});assert.equal(recurring.response.status,201);
 const apiKey=await request('/api/enterprise/api-keys',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Reporting integration',scopes:['read']})});assert.equal(apiKey.response.status,201);const apiAccess=await request('/api/bootstrap',{headers:{Authorization:`Bearer ${apiKey.data.key}`}});assert.equal(apiAccess.response.status,200);assert.equal(apiAccess.data.profile.companyName,'Acme Studio');
 const writeKey=await request('/api/enterprise/api-keys',{cookie:first.cookie,method:'POST',body:JSON.stringify({name:'Automation integration',scopes:['read','write']})});const idempotentHeaders={Authorization:`Bearer ${writeKey.data.key}`,'Idempotency-Key':'create-client-001'},automatedClient=await request('/api/clients',{method:'POST',headers:idempotentHeaders,body:JSON.stringify({name:'API Client'})}),replayedClient=await request('/api/clients',{method:'POST',headers:idempotentHeaders,body:JSON.stringify({name:'API Client'})});assert.equal(automatedClient.response.status,201);assert.equal(replayedClient.data.id,automatedClient.data.id);assert.equal(replayedClient.response.headers.get('idempotent-replayed'),'true');
 const audit=await request('/api/enterprise/audit',{cookie:first.cookie});assert.equal(audit.response.status,200);assert.ok(audit.data.audit.length>=10);
 const exported=await request('/api/account/export',{cookie:first.cookie});assert.equal(exported.data.profile.companyName,'Acme Studio');assert.equal(exported.data.invoices[0].items[0].description,'Design updated');
 const readiness=await request('/api/enterprise/readiness',{cookie:first.cookie});assert.equal(readiness.response.status,200);assert.equal(readiness.data.ready,false);
 const mfaSetup=await request('/api/security/mfa/setup',{cookie:first.cookie,method:'POST',body:'{}'});assert.equal(mfaSetup.response.status,200);assert.equal((await request('/api/security/mfa/enable',{cookie:first.cookie,method:'POST',body:JSON.stringify({code:totp(mfaSetup.data.secret)})})).response.status,200);
 const logout=await request('/api/auth/logout',{cookie:first.cookie,method:'POST',body:'{}'});assert.equal(logout.response.status,200);const denied=await request('/api/bootstrap',{cookie:first.cookie});assert.equal(denied.response.status,401);assert.equal((await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'a-secure-password'})})).response.status,401);const mfaLogin=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'a-secure-password',mfaCode:totp(mfaSetup.data.secret)})});assert.equal(mfaLogin.response.status,200);
 const reset=await request('/api/auth/password/request',{method:'POST',body:JSON.stringify({email:'owner@example.com'})});assert.ok(reset.data.resetToken);assert.equal((await request('/api/auth/password/reset',{method:'POST',body:JSON.stringify({token:reset.data.resetToken,password:'a-new-secure-password'})})).response.status,200);assert.equal((await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:'owner@example.com',password:'a-new-secure-password',mfaCode:totp(mfaSetup.data.secret)})})).response.status,200);
}

test('core bookkeeping and enterprise governance flow on SQLite',t=>coreFlow(t));
if(process.env.TEST_DATABASE_URL)test('core bookkeeping and enterprise governance flow on PostgreSQL',t=>coreFlow(t,process.env.TEST_DATABASE_URL));
