let clients=[];
let invoices=[];
let expenses=[];
let profile={companyName:'',ownerName:'',email:'',phone:'',taxId:'',vatNumber:'',address:'',currency:'ZAR',logo:'',subscriptionStatus:'trialing'};
let activeFilter='all',activeExpenseFilter='all',authMode='login',previewedInvoice=null,editingInvoiceId=null,editingClientId=null,editingExpenseId=null;
let enterpriseData={role:'viewer',permissions:[],organizations:[],members:[],approvals:[],approvalRules:[],notifications:[],connections:[],bankAccounts:[],bankTransactions:[],accounts:[],journals:[],statements:{},documents:[],payrollRuns:[],files:[],recurring:[],apiKeys:[],webhooks:[],webhookDeliveries:[]};
const currencyLocales={EUR:'en-IE',ZAR:'en-ZA',USD:'en-US',GBP:'en-GB',AUD:'en-AU',CAD:'en-CA',NGN:'en-NG',KES:'en-KE'};
let money=createMoneyFormatter();
const $=id=>document.getElementById(id);

async function api(path,options={}){
 const response=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
 const result=await response.json().catch(()=>({}));
 if(!response.ok)throw new Error(result.error||'Something went wrong');
 return result;
}
function createMoneyFormatter(){return new Intl.NumberFormat(currencyLocales[profile.currency]||'en-ZA',{style:'currency',currency:profile.currency||'ZAR'})}
function shortDate(value){return value?new Intl.DateTimeFormat('en-ZA',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value+'T12:00:00')):'—'}
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function initials(name){return String(name||'?').split(/\s|&/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function clientFor(id){return clients.find(c=>Number(c.id)===Number(id))||{name:'Unknown client',email:'',address:'',vatNumber:'',color:'#eee'}}
function subtotal(inv){return inv.items.reduce((sum,item)=>sum+Number(item.qty)*Number(item.rate),0)}
function total(inv){const afterDiscount=Math.max(0,subtotal(inv)-Number(inv.discount||0));return afterDiscount*(1+Number(inv.taxRate||0)/100)}
function displayStatus(item){return item.status==='sent'&&item.due<new Date().toISOString().slice(0,10)?'overdue':item.status}
function showToast(message,error=false){const toast=$('toast');toast.querySelector('p').textContent=message;toast.classList.toggle('error',error);toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
function openModal(id){const el=$(id);el.classList.add('open');el.setAttribute('aria-hidden','false');setTimeout(()=>el.querySelector('input,select,textarea,button')?.focus(),0)}
function closeModal(id){const el=$(id);el.classList.remove('open');el.setAttribute('aria-hidden','true')}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(view+'View').classList.add('active');document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function download(name,data,type='application/json'){const blob=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}

function setAuthMode(mode){authMode=mode;const register=mode==='register';$('registrationFields').hidden=!register;$('mfaLoginField').hidden=register;$('forgotPassword').hidden=register;$('authCompany').required=register;$('authOwner').required=register;$('authTitle').textContent=register?'Start your free trial':'Welcome back';$('authIntro').textContent=register?'Every finance-operations feature, no card required.':'Sign in to your finance workspace.';$('authSubmit').textContent=register?'Create my workspace':'Sign in';$('authSwitch').textContent=register?'Already have an account? Sign in':'New to ledgerIQ? Start your free trial';$('authPassword').autocomplete=register?'new-password':'current-password';$('authError').textContent=''}
async function loadApp(){const [data,enterprise,security]=await Promise.all([api('/api/bootstrap'),api('/api/enterprise/summary'),api('/api/security/status')]);profile=data.profile;clients=data.clients;invoices=data.invoices;expenses=data.expenses;enterpriseData=enterprise;money=createMoneyFormatter();$('authScreen').hidden=true;$('appShell').hidden=false;populateProfileForm();renderSecurity(security);renderAll()}
async function start(){const params=new URLSearchParams(location.search),verify=params.get('verify'),reset=params.get('reset');if(verify){try{await api('/api/auth/verify-email',{method:'POST',body:JSON.stringify({token:verify})});history.replaceState({},'',location.pathname);showToast('Email verified')}catch(error){showToast(error.message,true)}}if(reset){const password=prompt('Choose a new password (at least 10 characters)');if(password)try{await api('/api/auth/password/reset',{method:'POST',body:JSON.stringify({token:reset,password})});history.replaceState({},'',location.pathname);showToast('Password changed. Sign in again.')}catch(error){showToast(error.message,true)}}try{await api('/api/me');await loadApp();const invite=params.get('invite');if(invite){await enterpriseAction('/invitations/accept',{method:'POST',body:JSON.stringify({token:invite})},'Invitation accepted');history.replaceState({},'',location.pathname)}}catch{$('authScreen').hidden=false;$('appShell').hidden=true}}
function renderSecurity(security){$('securityStatus').textContent=`${security.emailVerifiedAt?'Verified email':'Email unverified'} · ${security.mfaEnabled?'MFA on':'MFA off'}`;$('setupMfa').textContent=security.mfaEnabled?'MFA enabled':'Set up MFA';$('setupMfa').disabled=Boolean(security.mfaEnabled);$('resendVerification').hidden=Boolean(security.emailVerifiedAt)}

function logoMarkup(){return profile.logo?`<img src="${profile.logo}" alt="${escapeHTML(profile.companyName)} logo">`:`<span>${initials(profile.companyName||profile.ownerName)}</span>`}
function populateProfileForm(){
 $('companyName').value=profile.companyName||'';$('ownerName').value=profile.ownerName||'';$('companyEmail').value=profile.email||'';$('companyPhone').value=profile.phone||'';$('companyTaxId').value=profile.taxId||'';$('companyVatNumber').value=profile.vatNumber||'';$('companyAddress').value=profile.address||'';$('companyCurrency').value=profile.currency||'ZAR';
 const first=(profile.ownerName||'there').split(/\s+/)[0];$('welcomeHeading').textContent=`Good morning, ${first}.`;$('accountName').textContent=profile.ownerName;$('accountCompany').textContent=profile.companyName;$('accountAvatar').innerHTML=logoMarkup();$('logoPreview').innerHTML=logoMarkup();$('supportEmail').value=profile.email||'';
 const trialDays=Math.max(0,Math.ceil((new Date(profile.trialEndsAt)-Date.now())/86400000));$('subscriptionStatus').textContent=profile.subscriptionStatus==='active'?'Active subscription':profile.subscriptionStatus==='trialing'?`${trialDays} day${trialDays===1?'':'s'} left in your free trial`:profile.subscriptionStatus.replace('_',' ');
}
function renderAll(){renderInvoices();renderClients();renderExpenses();renderReports();renderMetrics();renderEnterprise()}
function invoiceRow(inv){const c=clientFor(inv.clientId),status=displayStatus(inv);return `<tr><td class="invoice-id">${escapeHTML(inv.number)}</td><td><div class="client-cell"><span class="client-avatar" style="background:${escapeHTML(c.color)}">${initials(c.name)}</span>${escapeHTML(c.name)}</div></td><td>${shortDate(inv.issue)}</td><td>${shortDate(inv.due)}</td><td><strong>${money.format(total(inv))}</strong></td><td><span class="status ${status}">${status}</span></td><td><div class="row-actions"><button data-preview="${inv.id}">View</button><button data-edit-invoice="${inv.id}">Edit</button>${status==='draft'?`<button data-send="${inv.id}">Send</button><button data-request-invoice="${inv.id}" data-amount="${total(inv)}">Approval</button>`:''}${status!=='paid'?`<button data-paid="${inv.id}">Paid</button>`:''}<button class="danger" data-delete-invoice="${inv.id}">Delete</button></div></td></tr>`}
function renderInvoices(){const search=($('invoiceSearch').value||'').toLowerCase(),filtered=invoices.filter(inv=>(activeFilter==='all'||displayStatus(inv)===activeFilter)&&`${inv.number} ${clientFor(inv.clientId).name}`.toLowerCase().includes(search));$('allInvoiceRows').innerHTML=filtered.length?filtered.map(invoiceRow).join(''):`<tr><td colspan="7" class="empty-state"><strong>No invoices found</strong>Create your first invoice or change the filter.</td></tr>`;$('recentInvoiceRows').innerHTML=invoices.slice(0,5).map(invoiceRow).join('');$('navInvoiceCount').textContent=invoices.length;bindInvoiceActions()}
function bindInvoiceActions(){document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>previewInvoice(Number(b.dataset.preview)));document.querySelectorAll('[data-edit-invoice]').forEach(b=>b.onclick=()=>startInvoice(invoices.find(i=>i.id===Number(b.dataset.editInvoice))));document.querySelectorAll('[data-request-invoice]').forEach(b=>b.onclick=()=>requestApproval('invoice',b.dataset.requestInvoice,Number(b.dataset.amount)));document.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>changeInvoiceStatus(Number(b.dataset.paid),'paid'));document.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>sendInvoice(Number(b.dataset.send)));document.querySelectorAll('[data-delete-invoice]').forEach(b=>b.onclick=()=>deleteInvoice(Number(b.dataset.deleteInvoice)))}
async function changeInvoiceStatus(id,status){try{await api(`/api/invoices/${id}`,{method:'PATCH',body:JSON.stringify({status,paidDate:new Date().toISOString().slice(0,10)})});await reload();showToast(`Invoice marked ${status}`)}catch(error){showToast(error.message,true)}}
async function sendInvoice(id){const button=document.querySelector(`[data-send="${id}"]`);if(button){button.disabled=true;button.textContent='Sending…'}try{await api(`/api/invoices/${id}/send`,{method:'POST'});await reload();showToast('Invoice emailed to the client')}catch(error){showToast(error.message,true);if(button){button.disabled=false;button.textContent='Send'}}}
async function deleteInvoice(id){if(!confirm('Delete this invoice permanently?'))return;try{await api(`/api/invoices/${id}`,{method:'DELETE'});await reload();showToast('Invoice deleted')}catch(error){showToast(error.message,true)}}
function renderClients(){$('clientGrid').innerHTML=clients.length?clients.map(c=>{const related=invoices.filter(i=>Number(i.clientId)===Number(c.id));return `<article class="panel client-card"><div class="client-top"><span class="client-avatar" style="background:${escapeHTML(c.color)}">${initials(c.name)}</span><div><h3>${escapeHTML(c.name)}</h3><p>${escapeHTML(c.email||'No email')}</p></div></div><p>${escapeHTML(c.address||'No billing address added yet.')}</p><div class="client-stats"><span>Invoices<strong>${related.length}</strong></span><span>Total billed<strong>${money.format(related.reduce((s,i)=>s+total(i),0))}</strong></span></div><button class="text-button" data-edit-client="${c.id}">Edit</button> <button class="text-button danger client-delete" data-delete-client="${c.id}">Delete</button></article>`}).join(''):`<article class="panel empty-card"><h2>Add your first client</h2><p>Clients you invoice will appear here.</p></article>`;document.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>startClient(clients.find(c=>c.id===Number(b.dataset.editClient))));document.querySelectorAll('[data-delete-client]').forEach(b=>b.onclick=()=>deleteClient(Number(b.dataset.deleteClient)))}
function startClient(client=null){editingClientId=client?.id||null;$('clientModalTitle').textContent=client?'Edit client':'Add client';$('clientName').value=client?.name||'';$('clientEmail').value=client?.email||'';$('clientAddress').value=client?.address||'';$('clientVatNumber').value=client?.vatNumber||'';openModal('clientModal')}
async function deleteClient(id){if(!confirm('Delete this client? Clients with invoices cannot be deleted.'))return;try{await api(`/api/clients/${id}`,{method:'DELETE'});await reload();showToast('Client deleted')}catch(error){showToast(error.message,true)}}
function expenseRow(expense){const status=expense.status==='due'&&expense.due<new Date().toISOString().slice(0,10)?'overdue':expense.status;return `<tr><td class="invoice-id">${escapeHTML(expense.reference)}</td><td>${escapeHTML(expense.vendor)}</td><td>${escapeHTML(expense.category)}</td><td>${shortDate(expense.date)}</td><td>${shortDate(expense.due)}</td><td><strong>${money.format(expense.amount)}</strong></td><td><span class="status ${status}">${status}</span></td><td><div class="row-actions"><button data-edit-expense="${expense.id}">Edit</button><button data-request-expense="${expense.id}" data-amount="${expense.amount}">Approval</button>${status!=='paid'?`<button data-expense-paid="${expense.id}">Paid</button>`:''}<button class="danger" data-delete-expense="${expense.id}">Delete</button></div></td></tr>`}
function renderExpenses(){const search=($('expenseSearch').value||'').toLowerCase(),filtered=expenses.filter(e=>{const status=e.status==='due'&&e.due<new Date().toISOString().slice(0,10)?'overdue':e.status;return(activeExpenseFilter==='all'||status===activeExpenseFilter)&&`${e.reference} ${e.vendor} ${e.category}`.toLowerCase().includes(search)});$('expenseRows').innerHTML=filtered.length?filtered.map(expenseRow).join(''):`<tr><td colspan="8" class="empty-state"><strong>No expenses found</strong>Add a supplier bill or change the filter.</td></tr>`;$('navExpenseCount').textContent=expenses.filter(e=>e.status!=='paid').length;document.querySelectorAll('[data-edit-expense]').forEach(b=>b.onclick=()=>startExpense(expenses.find(e=>e.id===Number(b.dataset.editExpense))));document.querySelectorAll('[data-request-expense]').forEach(b=>b.onclick=()=>requestApproval('expense',b.dataset.requestExpense,Number(b.dataset.amount)));document.querySelectorAll('[data-expense-paid]').forEach(b=>b.onclick=()=>changeExpenseStatus(Number(b.dataset.expensePaid),'paid'));document.querySelectorAll('[data-delete-expense]').forEach(b=>b.onclick=()=>deleteExpense(Number(b.dataset.deleteExpense)));renderExpenseMetrics()}
async function changeExpenseStatus(id,status){try{await api(`/api/expenses/${id}`,{method:'PATCH',body:JSON.stringify({status})});await reload();showToast('Expense marked paid')}catch(error){showToast(error.message,true)}}
async function deleteExpense(id){if(!confirm('Delete this expense permanently?'))return;try{await api(`/api/expenses/${id}`,{method:'DELETE'});await reload();showToast('Expense deleted')}catch(error){showToast(error.message,true)}}
function currentMonth(){return new Date().toISOString().slice(0,7)}
function renderExpenseMetrics(){const month=currentMonth(),paid=expenses.filter(e=>e.status==='paid'&&(e.paidDate||e.date).startsWith(month)),due=expenses.filter(e=>e.status==='due'&&e.due>=new Date().toISOString().slice(0,10)),overdue=expenses.filter(e=>e.status==='overdue'||(e.status==='due'&&e.due<new Date().toISOString().slice(0,10))),sum=list=>list.reduce((s,e)=>s+Number(e.amount),0);$('expensePaidMetric').textContent=money.format(sum(paid));$('expenseDueMetric').textContent=money.format(sum(due));$('expenseOverdueMetric').textContent=money.format(sum(overdue));$('expenseDueCount').textContent=`${due.length} bill${due.length===1?'':'s'}`;$('expenseOverdueCount').textContent=`${overdue.length} bill${overdue.length===1?'':'s'}`;const income=invoices.filter(i=>i.status==='paid'&&(i.paidDate||i.issue).startsWith(month)).reduce((s,i)=>s+total(i),0),profit=income-sum(paid),flow=income+sum(paid);['monthlyIncome','reportIncome'].forEach(id=>$(id).textContent=money.format(income));['monthlyExpenses','reportExpenses'].forEach(id=>$(id).textContent=money.format(sum(paid)));['monthlyProfit','reportProfit'].forEach(id=>$(id).textContent=money.format(profit));$('profitMargin').textContent=`${income?Math.round(profit/income*100):0}% margin`;$('incomeBar').style.width=`${flow?income/flow*100:0}%`;$('expenseBar').style.width=`${flow?sum(paid)/flow*100:0}%`}
function renderMetrics(){const paid=invoices.filter(i=>i.status==='paid').reduce((s,i)=>s+total(i),0),sent=invoices.filter(i=>displayStatus(i)==='sent').reduce((s,i)=>s+total(i),0),overdue=invoices.filter(i=>displayStatus(i)==='overdue').reduce((s,i)=>s+total(i),0),all=paid+sent+overdue;$('revenueMetric').textContent=money.format(all);$('paidMetric').textContent=money.format(paid);$('outstandingMetric').textContent=money.format(sent);$('overdueMetric').textContent=money.format(overdue);$('outstandingCount').textContent=`${invoices.filter(i=>displayStatus(i)==='sent').length} invoices`;$('overdueCount').textContent=`${invoices.filter(i=>displayStatus(i)==='overdue').length} invoices`;const rate=all?Math.round(paid/all*100):0;$('paymentRate').textContent=rate+'%';$('paymentDonut').style.setProperty('--rate',rate+'%');$('healthPaid').textContent=money.format(paid);$('healthOutstanding').textContent=money.format(sent);$('healthOverdue').textContent=money.format(overdue);const compact=new Intl.NumberFormat(currencyLocales[profile.currency]||'en-ZA',{style:'currency',currency:profile.currency,notation:'compact',maximumFractionDigits:0});$('revenueAxis').innerHTML=[15000,10000,5000,0].map(v=>`<span>${compact.format(v)}</span>`).join('');$('chartTotal').innerHTML=`${money.format(paid)} <small>Total</small>`}
function renderReports(){const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);return{key:d.toISOString().slice(0,7),label:d.toLocaleString('en-ZA',{month:'short'})}}),values=months.map(m=>invoices.filter(i=>i.status==='paid'&&(i.paidDate||i.issue).startsWith(m.key)).reduce((s,i)=>s+total(i),0)),max=Math.max(...values,1);$('revenueChart').innerHTML=months.map((m,i)=>`<div class="bar-group"><i style="--h:${Math.max(2,values[i]/max*100)}%"></i><span>${m.label}</span></div>`).join('');$('reportBars').innerHTML=months.map((m,i)=>`<div class="large-bar" title="${money.format(values[i])}" style="--h:${Math.max(2,values[i]/max*100)}%"><span>${m.label}</span></div>`).join('')}

function previewInvoice(id){const inv=invoices.find(i=>i.id===id),c=clientFor(inv.clientId),sub=subtotal(inv),discount=Number(inv.discount||0),taxable=Math.max(0,sub-discount),tax=taxable*Number(inv.taxRate||0)/100;previewedInvoice=inv;const sender=[profile.address,profile.email,profile.phone,profile.taxId&&`Registration: ${profile.taxId}`,profile.vatNumber&&`VAT: ${profile.vatNumber}`].filter(Boolean).map(escapeHTML).join('<br>'),recipient=[c.address,c.email,c.vatNumber&&`VAT: ${c.vatNumber}`].filter(Boolean).map(escapeHTML).join('<br>');$('invoicePaper').innerHTML=`<div class="paper-head"><div class="paper-logo">${logoMarkup()} ${escapeHTML(profile.companyName)}</div><div class="paper-title"><h2>INVOICE</h2><p>${escapeHTML(inv.number)}</p></div></div><div class="paper-parties"><div><small>From</small><h3>${escapeHTML(profile.companyName)}</h3><p>${sender}</p></div><div><small>Bill to</small><h3>${escapeHTML(c.name)}</h3><p>${recipient}</p></div></div><table class="paper-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${inv.items.map(i=>`<tr><td>${escapeHTML(i.description)}</td><td>${i.qty}</td><td>${escapeHTML(i.unit||'—')}</td><td>${money.format(i.rate)}</td><td>${money.format(i.qty*i.rate)}</td></tr>`).join('')}</tbody></table><div class="paper-total"><div><span>Subtotal</span><strong>${money.format(sub)}</strong></div>${discount?`<div><span>Discount</span><strong>-${money.format(discount)}</strong></div>`:''}<div><span>VAT / tax (${inv.taxRate||0}%)</span><strong>${money.format(tax)}</strong></div><div class="grand"><span>Total</span><strong>${money.format(total(inv))}</strong></div></div><div class="paper-note"><strong>Notes</strong><p>${escapeHTML(inv.notes||'Thank you for your business.')}</p>${inv.paymentDetails?`<strong>Payment details</strong><p>${escapeHTML(inv.paymentDetails)}</p>`:''}<p>Issued ${shortDate(inv.issue)} · Due ${shortDate(inv.due)}</p></div>`;openModal('previewModal')}
function addLine(description='',qty=1,rate='',unit=''){const line=document.createElement('div');line.className='line-item';line.innerHTML=`<input class="line-desc" placeholder="Description" value="${escapeHTML(description)}" required><input class="line-qty" type="number" min="0.01" step="0.01" value="${qty}" required><input class="line-unit" list="unitPresets" placeholder="Unit" value="${escapeHTML(unit)}"><input class="line-rate" type="number" min="0" step="0.01" placeholder="Rate" value="${rate}" required><button type="button" class="remove-line">×</button>`;$('lineItems').appendChild(line);line.querySelector('.remove-line').onclick=()=>{line.remove();updateFormTotal()};line.querySelectorAll('input').forEach(input=>input.addEventListener('input',updateFormTotal));updateFormTotal()}
function updateFormTotal(){const sub=[...document.querySelectorAll('.line-item')].reduce((s,line)=>s+(+line.querySelector('.line-qty').value||0)*(+line.querySelector('.line-rate').value||0),0),discount=+$('invoiceDiscount').value||0,tax=+$('invoiceTaxRate').value||0;$('formTotal').textContent=money.format(Math.max(0,sub-discount)*(1+tax/100))}
function startInvoice(inv=null){if(!inv?.items)inv=null;if(!clients.length){showToast('Add a client before creating an invoice',true);switchView('clients');return}editingInvoiceId=inv?.id||null;$('invoiceModalTitle').textContent=inv?'Edit invoice':'Create invoice';$('invoiceClient').innerHTML=clients.map(c=>`<option value="${c.id}">${escapeHTML(c.name)}</option>`).join('');const next=Math.max(...invoices.map(i=>parseInt(i.number.replace(/\D/g,''))||0),0)+1,today=new Date(),due=new Date();due.setDate(today.getDate()+14);$('invoiceClient').value=inv?.clientId||clients[0].id;$('invoiceNumber').value=inv?.number||'INV-'+String(next).padStart(4,'0');$('issueDate').value=inv?.issue||today.toISOString().slice(0,10);$('dueDate').value=inv?.due||due.toISOString().slice(0,10);$('invoiceTaxRate').value=inv?.taxRate??(profile.vatNumber?'15':'0');$('invoiceDiscount').value=inv?.discount||'0';$('invoiceNotes').value=inv?.notes||'Payment due within 14 days.';$('invoicePaymentDetails').value=inv?.paymentDetails||'';$('lineItems').innerHTML='';(inv?.items||[{description:'',qty:1,rate:'',unit:''}]).forEach(i=>addLine(i.description,i.qty,i.rate,i.unit));openModal('invoiceModal')}
function startExpense(exp=null){if(!exp?.reference)exp=null;editingExpenseId=exp?.id||null;$('expenseModalTitle').textContent=exp?'Edit expense or bill':'Add expense or bill';const next=Math.max(...expenses.map(e=>parseInt(e.reference.replace(/\D/g,''))||0),0)+1,today=new Date(),due=new Date();due.setDate(today.getDate()+14);$('expenseVendor').value=exp?.vendor||'';$('expenseNumber').value=exp?.reference||'BILL-'+String(next).padStart(4,'0');$('expenseCategory').value=exp?.category||'Software';$('expenseAmount').value=exp?.amount||'';$('expenseDate').value=exp?.date||today.toISOString().slice(0,10);$('expenseDueDate').value=exp?.due||due.toISOString().slice(0,10);$('expenseStatus').value=exp?.status||'due';$('expenseNotes').value=exp?.notes||'';openModal('expenseModal')}
async function reload(){const [data,enterprise]=await Promise.all([api('/api/bootstrap'),api('/api/enterprise/summary')]);profile=data.profile;clients=data.clients;invoices=data.invoices;expenses=data.expenses;enterpriseData=enterprise;money=createMoneyFormatter();populateProfileForm();renderAll()}
function exportCSV(){const rows=[['Type','Reference','Client / supplier','Category','Date','Due date','Subtotal','Tax','Total','Currency','Status'],...invoices.map(i=>['Income',i.number,clientFor(i.clientId).name,'Sales',i.issue,i.due,subtotal(i),(Math.max(0,subtotal(i)-i.discount)*i.taxRate/100),total(i),profile.currency,displayStatus(i)]),...expenses.map(e=>['Expense',e.reference,e.vendor,e.category,e.date,e.due,e.amount,0,e.amount,profile.currency,e.status])],csv=rows.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');download('ledgeriq-report.csv',csv,'text/csv')}

function hasPermission(permission){return enterpriseData.permissions.includes('*')||enterpriseData.permissions.includes(permission)}
function compactEmpty(message){return `<div class="empty-compact">${escapeHTML(message)}</div>`}
function renderEnterprise(){
 $('enterpriseOrgSelect').innerHTML=enterpriseData.organizations.map(o=>`<option value="${o.id}" ${o.id===enterpriseData.activeOrganizationId?'selected':''}>${escapeHTML(o.name)}</option>`).join('');
 $('enterpriseRole').textContent=enterpriseData.role.replaceAll('_',' ');const pending=enterpriseData.approvals.filter(a=>a.status==='pending'),unmatched=enterpriseData.bankTransactions.filter(t=>t.status==='unmatched');$('pendingApprovalCount').textContent=pending.length;$('enterpriseApprovalMetric').textContent=pending.length;$('enterpriseBankMetric').textContent=unmatched.length;$('enterpriseConnectionMetric').textContent=enterpriseData.connections.length;
 $('teamRows').innerHTML=enterpriseData.members.length?enterpriseData.members.map(m=>`<div class="compact-row"><div><strong>${escapeHTML(m.email)}</strong><small>Joined ${shortDate(String(m.createdAt).slice(0,10))}</small></div>${m.role==='owner'?`<span class="role-pill">owner</span>`:`<select data-member-role="${m.id}" ${hasPermission('manage_team')?'':'disabled'}>${['admin','finance_manager','approver','accountant','employee','viewer'].map(r=>`<option value="${r}" ${r===m.role?'selected':''}>${r.replaceAll('_',' ')}</option>`).join('')}</select>`}</div>`).join(''):compactEmpty('No team members yet.');
 $('approvalRows').innerHTML=enterpriseData.approvals.length?enterpriseData.approvals.map(a=>`<div class="compact-row"><div><strong>${escapeHTML(a.entity_type.replaceAll('_',' '))} · ${escapeHTML(a.entity_id)}</strong><small>${money.format(a.amount)} · ${shortDate(String(a.created_at).slice(0,10))}</small></div><span class="status ${a.status==='approved'?'paid':a.status==='rejected'?'overdue':'sent'}">${a.status}</span>${a.status==='pending'&&hasPermission('approve')?`<button data-approval-decision="${a.id}" data-status="approved">Approve</button><button class="danger" data-approval-decision="${a.id}" data-status="rejected">Reject</button>`:''}</div>`).join(''):compactEmpty('No approval requests.');
 $('approvalRuleRows').innerHTML=(enterpriseData.approvalRules||[]).length?enterpriseData.approvalRules.map(r=>`<div class="compact-row"><div><strong>${escapeHTML(r.entityType.replaceAll('_',' '))} from ${money.format(r.minAmount)}</strong><small>${r.requiredApprovals} required approver${r.requiredApprovals===1?'':'s'}</small></div>${hasPermission('manage_org')?`<button class="danger" data-delete-rule="${r.id}">Delete</button>`:''}</div>`).join(''):compactEmpty('No amount-based rules. One approval is required by default.');
 $('connectionRows').innerHTML=enterpriseData.connections.length?enterpriseData.connections.map(c=>`<div class="compact-row"><div><strong>${escapeHTML(c.displayName)}</strong><small>${escapeHTML(c.category)} · ${escapeHTML(c.provider)}${c.lastSyncAt?` · synced ${shortDate(c.lastSyncAt.slice(0,10))}`:''}${c.lastError?` · ${escapeHTML(c.lastError)}`:''}</small></div><span class="status ${c.status==='connected'?'paid':'draft'}">${c.status}</span>${hasPermission('manage_integrations')?`${c.provider.toLowerCase()==='xero'?'<button data-xero-oauth>Authorise Xero</button>':''}<button data-configure-connection="${c.id}">Credentials</button><button data-sync-connection="${c.id}">Sync</button><button class="danger" data-disconnect-connection="${c.id}">Disconnect</button>`:''}</div>`).join(''):compactEmpty('No providers connected.');
 $('bankAccountRows').innerHTML=enterpriseData.bankAccounts.length?enterpriseData.bankAccounts.map(a=>`<div class="compact-row"><div><strong>${escapeHTML(a.name)} · ${escapeHTML(a.currency)}</strong><small>${escapeHTML(a.accountNumberMasked||'No account number')} · ${money.format(a.balance)}</small></div>${hasPermission('manage_finance')?`<button data-import-bank="${a.id}">Import transaction</button>`:''}</div>`).join(''):compactEmpty('No bank accounts.');
 $('bankTransactionRows').innerHTML=enterpriseData.bankTransactions.length?enterpriseData.bankTransactions.slice(0,20).map(t=>`<div class="compact-row"><div><strong>${escapeHTML(t.description)}</strong><small>${shortDate(t.date)} · ${new Intl.NumberFormat('en-ZA',{style:'currency',currency:t.currency}).format(t.amount)}</small></div><span class="status ${t.status==='matched'?'paid':'draft'}">${t.status}</span>${t.status==='unmatched'&&hasPermission('manage_finance')?`<button data-match-bank="${t.id}">Match</button>`:''}</div>`).join(''):compactEmpty('No bank-feed transactions.');
 const statements=enterpriseData.statements||{};$('ledgerRevenue').textContent=money.format(statements.revenue||0);$('ledgerExpenses').textContent=money.format(statements.expenses||0);$('ledgerProfit').textContent=money.format(statements.netProfit||0);$('ledgerAssets').textContent=money.format(statements.assets||0);$('ledgerLiabilities').textContent=money.format(statements.liabilities||0);const accountOptions=(enterpriseData.accounts||[]).filter(a=>a.active).map(a=>`<option value="${a.id}">${escapeHTML(a.code)} · ${escapeHTML(a.name)}</option>`).join('');$('journalDebitAccount').innerHTML=`<option value="">Debit account</option>${accountOptions}`;$('journalCreditAccount').innerHTML=`<option value="">Credit account</option>${accountOptions}`;$('ledgerAccountRows').innerHTML=(enterpriseData.accounts||[]).map(a=>`<div class="compact-row"><div><strong>${escapeHTML(a.code)} · ${escapeHTML(a.name)}</strong><small>${escapeHTML(a.type)} · ${money.format(a.balance)}</small></div></div>`).join('')||compactEmpty('No ledger accounts.');$('journalRows').innerHTML=(enterpriseData.journals||[]).map(j=>`<div class="compact-row"><div><strong>${escapeHTML(j.reference)}</strong><small>${shortDate(j.entryDate)} · ${escapeHTML(j.memo||j.source)} · ${money.format(j.total)}</small></div><span class="status paid">posted</span></div>`).join('')||compactEmpty('No posted journals.');
 $('businessDocumentRows').innerHTML=enterpriseData.documents.length?enterpriseData.documents.map(d=>`<div class="compact-row"><div><strong>${escapeHTML(d.number)} · ${escapeHTML(d.counterparty)}</strong><small>${escapeHTML(d.type.replaceAll('_',' '))} · ${money.format(d.total)}</small></div><span class="status draft">${escapeHTML(d.status)}</span></div>`).join(''):compactEmpty('No quotes, purchase orders or credit notes.');
 $('payrollRows').innerHTML=enterpriseData.payrollRuns.length?enterpriseData.payrollRuns.map(p=>`<div class="compact-row"><div><strong>${escapeHTML(p.provider)} · ${shortDate(p.periodEnd)}</strong><small>${p.employeeCount} employees · ${money.format(p.net)} net</small></div><span class="status draft">${escapeHTML(p.status)}</span>${hasPermission('submit')||hasPermission('manage_finance')?`<button data-request-payroll="${p.id}" data-amount="${p.net}">Request approval</button>`:''}</div>`).join(''):compactEmpty('No payroll runs.');
 $('apiKeyRows').innerHTML=[...(enterpriseData.apiKeys||[]).map(k=>`<div class="compact-row"><div><strong>${escapeHTML(k.name)}</strong><small>${escapeHTML(k.keyPrefix)}… · API key</small></div></div>`),...(enterpriseData.webhooks||[]).map(w=>`<div class="compact-row"><div><strong>Webhook</strong><small>${escapeHTML(w.url)}</small></div><span class="status ${w.active?'paid':'draft'}">${w.active?'active':'off'}</span></div>`)].join('')||compactEmpty('No API keys or webhooks.');
 $('automationRows').innerHTML=[...(enterpriseData.files||[]).map(f=>`<div class="compact-row"><div><strong>${escapeHTML(f.originalName)}</strong><small>${escapeHTML(f.entityType)} · ${(f.size/1024).toFixed(1)} KB</small></div><span class="role-pill">file</span></div>`),...(enterpriseData.recurring||[]).map(r=>`<div class="compact-row"><div><strong>${escapeHTML(r.name)}</strong><small>${escapeHTML(r.frequency)} ${escapeHTML(r.templateType)} · next ${shortDate(r.nextRunDate)}</small></div><span class="status ${r.active?'paid':'draft'}">${r.active?'active':'stopped'}</span></div>`)].join('')||compactEmpty('No uploaded files or recurring automations.');
 $('notificationRows').innerHTML=(enterpriseData.notifications||[]).length?enterpriseData.notifications.map(n=>`<div class="compact-row"><div><strong>${escapeHTML(n.title)}</strong><small>${escapeHTML(n.message)} · ${new Date(n.createdAt).toLocaleString('en-ZA')}</small></div><span class="status ${n.readAt?'draft':'sent'}">${n.readAt?'read':'new'}</span></div>`).join(''):compactEmpty('No notifications.');
 $('webhookDeliveryRows').innerHTML=(enterpriseData.webhookDeliveries||[]).length?enterpriseData.webhookDeliveries.map(d=>`<div class="compact-row"><div><strong>${escapeHTML(d.event)}</strong><small>${escapeHTML(d.url)} · ${d.httpStatus||'no response'} · ${d.attempts} attempt${d.attempts===1?'':'s'}</small></div><span class="status ${d.status==='delivered'?'paid':d.status==='failed'?'overdue':'draft'}">${d.status}</span></div>`).join(''):compactEmpty('No webhook deliveries.');
 document.querySelectorAll('[data-member-role]').forEach(select=>select.onchange=()=>changeMemberRole(select.dataset.memberRole,select.value));document.querySelectorAll('[data-approval-decision]').forEach(button=>button.onclick=()=>decideApproval(button.dataset.approvalDecision,button.dataset.status));document.querySelectorAll('[data-delete-rule]').forEach(button=>button.onclick=()=>enterpriseAction(`/approval-rules/${button.dataset.deleteRule}`,{method:'DELETE'},'Approval rule deleted').catch(()=>{}));document.querySelectorAll('[data-xero-oauth]').forEach(button=>button.onclick=async()=>{try{const result=await api('/api/enterprise/oauth/xero/start',{method:'POST',body:'{}'});location.href=result.url}catch(error){showToast(error.message,true)}});document.querySelectorAll('[data-configure-connection]').forEach(button=>button.onclick=()=>configureConnection(button.dataset.configureConnection));document.querySelectorAll('[data-sync-connection]').forEach(button=>button.onclick=()=>syncConnection(button.dataset.syncConnection));document.querySelectorAll('[data-disconnect-connection]').forEach(button=>button.onclick=()=>enterpriseAction(`/connections/${button.dataset.disconnectConnection}`,{method:'DELETE'},'Provider disconnected').catch(()=>{}));document.querySelectorAll('[data-import-bank]').forEach(button=>button.onclick=()=>importBankTransaction(button.dataset.importBank));document.querySelectorAll('[data-match-bank]').forEach(button=>button.onclick=()=>matchBankTransaction(button.dataset.matchBank));document.querySelectorAll('[data-request-payroll]').forEach(button=>button.onclick=()=>requestApproval('payroll_run',button.dataset.requestPayroll,Number(button.dataset.amount)));
}
async function enterpriseAction(path,options,message){try{const result=await api('/api/enterprise'+path,options);await reload();if(message)showToast(message);return result}catch(error){showToast(error.message,true);throw error}}
async function changeMemberRole(userId,role){await enterpriseAction(`/members/${userId}`,{method:'PATCH',body:JSON.stringify({role})},'Member role updated').catch(()=>{})}
async function decideApproval(id,status){await enterpriseAction(`/approvals/${id}`,{method:'PATCH',body:JSON.stringify({status,note:''})},`Request ${status}`).catch(()=>{})}
async function requestApproval(entityType,entityId,amount){await enterpriseAction('/approvals',{method:'POST',body:JSON.stringify({entityType,entityId:String(entityId),amount})},'Approval requested').catch(()=>{})}
async function configureConnection(id){const input=prompt('Paste the provider credentials as JSON. They are encrypted before storage.');if(!input)return;try{const credentials=JSON.parse(input);await enterpriseAction(`/connections/${id}`,{method:'PATCH',body:JSON.stringify({credentials})},'Provider credentials encrypted and saved')}catch(error){if(error instanceof SyntaxError)showToast('Credentials must be valid JSON',true)}}
async function syncConnection(id){await enterpriseAction(`/connections/${id}/sync`,{method:'POST',body:'{}'},'Provider sync queued').catch(()=>{})}
async function importBankTransaction(bankAccountId){const date=prompt('Transaction date (YYYY-MM-DD)',new Date().toISOString().slice(0,10)),description=prompt('Transaction description'),amount=prompt('Amount (use a negative number for money out)');if(!date||!description||amount===null)return;await enterpriseAction('/bank-transactions/import',{method:'POST',body:JSON.stringify({bankAccountId,transactions:[{externalId:cryptoRandomId(),date,description,amount:Number(amount),currency:profile.currency}]})},'Bank transaction imported').catch(()=>{})}
function cryptoRandomId(){return `${Date.now()}-${Math.random().toString(36).slice(2)}`}
async function matchBankTransaction(id){const matchedType=prompt('Match type: invoice, expense, payroll_run, or other','invoice'),matchedId=prompt('Enter the matching record ID');if(!matchedType||!matchedId)return;await enterpriseAction(`/bank-transactions/${id}/match`,{method:'POST',body:JSON.stringify({matchedType,matchedId})},'Transaction reconciled').catch(()=>{})}
async function loadAudit(){try{const data=await api('/api/enterprise/audit');$('auditRows').innerHTML=data.audit.length?data.audit.map(a=>`<div class="audit-line"><strong>${escapeHTML(a.action.replaceAll('_',' '))}</strong><span>${escapeHTML(a.entityType)} ${escapeHTML(a.entityId||'')}</span><span>${escapeHTML(a.userEmail)}</span><span>${new Date(a.createdAt).toLocaleString('en-ZA')}</span></div>`).join(''):compactEmpty('No audit activity yet.')}catch(error){$('auditRows').innerHTML=compactEmpty(error.message)}}

$('authSwitch').onclick=()=>setAuthMode(authMode==='login'?'register':'login');
$('authForm').onsubmit=async event=>{event.preventDefault();$('authError').textContent='';$('authSubmit').disabled=true;try{const payload={email:$('authEmail').value,password:$('authPassword').value,mfaCode:$('authMfa').value,companyName:$('authCompany').value,ownerName:$('authOwner').value};await api(`/api/auth/${authMode}`,{method:'POST',body:JSON.stringify(payload)});event.target.reset();await loadApp()}catch(error){$('authError').textContent=error.message}finally{$('authSubmit').disabled=false}};
$('forgotPassword').onclick=async()=>{const address=prompt('Enter the email address on your account',$('authEmail').value);if(!address)return;try{const result=await api('/api/auth/password/request',{method:'POST',body:JSON.stringify({email:address})});if(result.resetToken)prompt('Email is not configured locally. Copy this development reset token:',result.resetToken);showToast('If that account exists, a reset link has been sent.')}catch(error){showToast(error.message,true)}};
document.querySelectorAll('.nav-item[data-view]').forEach(button=>button.onclick=()=>switchView(button.dataset.view));document.querySelectorAll('[data-view-link]').forEach(button=>button.onclick=()=>switchView(button.dataset.viewLink));document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>closeModal(button.dataset.close));document.querySelectorAll('.modal-backdrop').forEach(modal=>modal.addEventListener('click',event=>{if(event.target===modal)closeModal(modal.id)}));
$('enterpriseOrgSelect').onchange=async e=>{try{await api('/api/enterprise/organizations/switch',{method:'POST',body:JSON.stringify({organizationId:e.target.value})});await reload();showToast('Active company switched')}catch(error){showToast(error.message,true)}};
$('newOrgButton').onclick=async()=>{const name=prompt('New company name');if(!name)return;const registrationNumber=prompt('Company registration number (optional)')||'',vatNumber=prompt('VAT number (optional)')||'';await enterpriseAction('/organizations',{method:'POST',body:JSON.stringify({name,registrationNumber,vatNumber,currency:profile.currency})},'Company created').catch(()=>{})};
$('inviteForm').onsubmit=async e=>{e.preventDefault();try{const result=await enterpriseAction('/invitations',{method:'POST',body:JSON.stringify({email:$('inviteEmail').value,role:$('inviteRole').value})},'Invitation created');e.target.reset();if(result.inviteToken){$('apiKeyOutput').hidden=false;$('apiKeyOutput').textContent=`Email delivery is not configured. Share this invite link securely:\n${location.origin}/app?invite=${result.inviteToken}`}}catch{}};
$('approvalRuleForm').onsubmit=async e=>{e.preventDefault();await enterpriseAction('/approval-rules',{method:'POST',body:JSON.stringify({entityType:$('approvalRuleType').value,minAmount:+$('approvalRuleAmount').value,requiredApprovals:+$('approvalRuleCount').value})},'Approval rule added').then(()=>e.target.reset()).catch(()=>{})};
$('connectionForm').onsubmit=async e=>{e.preventDefault();await enterpriseAction('/connections',{method:'POST',body:JSON.stringify({category:$('connectionCategory').value,provider:$('connectionProvider').value,displayName:$('connectionName').value})},'Provider connection created').then(()=>e.target.reset()).catch(()=>{})};
$('bankAccountForm').onsubmit=async e=>{e.preventDefault();await enterpriseAction('/bank-accounts',{method:'POST',body:JSON.stringify({name:$('bankAccountName').value,accountNumberMasked:$('bankAccountMask').value,currency:$('bankAccountCurrency').value,balance:0})},'Bank account added').then(()=>e.target.reset()).catch(()=>{})};
$('ledgerAccountForm').onsubmit=async e=>{e.preventDefault();await enterpriseAction('/accounts',{method:'POST',body:JSON.stringify({code:$('ledgerAccountCode').value,name:$('ledgerAccountName').value,type:$('ledgerAccountType').value})},'Ledger account added').then(()=>e.target.reset()).catch(()=>{})};
$('journalForm').onsubmit=async e=>{e.preventDefault();const amount=+$('journalAmount').value,payload={reference:$('journalReference').value,entryDate:$('journalDate').value,memo:$('journalMemo').value,source:'manual',lines:[{accountId:$('journalDebitAccount').value,debit:amount,credit:0},{accountId:$('journalCreditAccount').value,debit:0,credit:amount}]};await enterpriseAction('/journals',{method:'POST',body:JSON.stringify(payload)},'Balanced journal posted').then(()=>e.target.reset()).catch(()=>{})};
$('periodLockForm').onsubmit=async e=>{e.preventDefault();if(!confirm('Locking a period prevents new journals in that date range. Continue?'))return;await enterpriseAction('/accounting-periods/lock',{method:'POST',body:JSON.stringify({startDate:$('periodStart').value,endDate:$('periodEnd').value})},'Accounting period locked').then(()=>e.target.reset()).catch(()=>{})};
$('businessDocumentForm').onsubmit=async e=>{e.preventDefault();await enterpriseAction('/documents',{method:'POST',body:JSON.stringify({type:$('businessDocumentType').value,number:$('businessDocumentNumber').value,counterparty:$('businessDocumentCounterparty').value,issueDate:new Date().toISOString().slice(0,10),status:'draft',total:+$('businessDocumentTotal').value,currency:profile.currency,payload:{}})},'Business document created').then(()=>e.target.reset()).catch(()=>{})};
$('payrollForm').onsubmit=async e=>{e.preventDefault();await enterpriseAction('/payroll-runs',{method:'POST',body:JSON.stringify({provider:$('payrollProvider').value,periodStart:$('payrollPeriodStart').value,periodEnd:$('payrollPeriodEnd').value,gross:+$('payrollNet').value,tax:0,net:+$('payrollNet').value,employeeCount:+$('payrollEmployees').value,status:'draft'})},'Payroll run added').then(()=>e.target.reset()).catch(()=>{})};
$('createApiKey').onclick=async()=>{const name=$('apiKeyName').value.trim();if(!name)return showToast('Enter an API key name',true);try{const result=await enterpriseAction('/api-keys',{method:'POST',body:JSON.stringify({name,scopes:['read','write']})},'API key created');$('apiKeyOutput').hidden=false;$('apiKeyOutput').textContent=`Copy this key now. It will not be shown again:\n${result.key}`;$('apiKeyName').value=''}catch{}};
$('webhookForm').onsubmit=async e=>{e.preventDefault();try{const result=await enterpriseAction('/webhooks',{method:'POST',body:JSON.stringify({url:$('webhookUrl').value,events:['*']})},'Webhook created');$('apiKeyOutput').hidden=false;$('apiKeyOutput').textContent=`Copy this webhook signing secret now:\n${result.secret}`;e.target.reset()}catch{}};
$('fileUploadForm').onsubmit=async e=>{e.preventDefault();const file=$('enterpriseFile').files[0];if(!file)return;if(file.size>5*1024*1024)return showToast('Files are limited to 5 MB',true);const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});await enterpriseAction('/files',{method:'POST',body:JSON.stringify({name:file.name,data,entityType:$('fileEntityType').value,entityId:$('fileEntityId').value})},'File uploaded').then(()=>e.target.reset()).catch(()=>{})};
$('recurringForm').onsubmit=async e=>{e.preventDefault();let payload;try{payload=JSON.parse($('recurringPayload').value)}catch{return showToast('Template payload must be valid JSON',true)}await enterpriseAction('/recurring',{method:'POST',body:JSON.stringify({name:$('recurringName').value,templateType:$('recurringType').value,frequency:$('recurringFrequency').value,nextRunDate:$('recurringDate').value,payload})},'Recurring automation scheduled').then(()=>e.target.reset()).catch(()=>{})};
$('readNotifications').onclick=()=>enterpriseAction('/notifications/read-all',{method:'POST',body:'{}'},'Notifications marked read').catch(()=>{});
$('resendVerification').onclick=async()=>{try{const result=await api('/api/security/verify/resend',{method:'POST',body:'{}'});if(result.token)prompt('Email is not configured locally. Copy this development verification token:',result.token);showToast(result.sent?'Verification email sent':'Verification token created')}catch(error){showToast(error.message,true)}};
$('setupMfa').onclick=async()=>{try{const setup=await api('/api/security/mfa/setup',{method:'POST',body:'{}'});$('mfaSetupOutput').hidden=false;$('mfaSetupOutput').textContent=`Add this secret to your authenticator app:\n${setup.secret}\n\n${setup.otpauth}`;const code=prompt('Enter the current 6-digit code from your authenticator');if(!code)return;await api('/api/security/mfa/enable',{method:'POST',body:JSON.stringify({code})});renderSecurity(await api('/api/security/status'));showToast('Multi-factor authentication enabled')}catch(error){showToast(error.message,true)}};
$('checkReadiness').onclick=async()=>{try{const result=await api('/api/enterprise/readiness');$('mfaSetupOutput').hidden=false;$('mfaSetupOutput').textContent=`Production readiness: ${result.ready?'READY':'ACTION REQUIRED'}\n\n${result.checks.map(c=>`${c.passed?'✓':'✗'} ${c.name}`).join('\n')}`}catch(error){showToast(error.message,true)}};
$('refreshAudit').onclick=loadAudit;
['newInvoiceTop','newInvoiceQuick','newInvoicePage'].forEach(id=>$(id).onclick=()=>startInvoice());['addClientQuick','addClientPage'].forEach(id=>$(id).onclick=()=>startClient());['newExpensePage','newExpenseQuick'].forEach(id=>$(id).onclick=()=>startExpense());
$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');$('addLine').onclick=()=>addLine();$('printInvoice').onclick=()=>window.print();$('exportReport').onclick=exportCSV;$('accountOptions').onclick=()=>switchView('settings');$('accountName').parentElement.onclick=()=>switchView('settings');$('billingNav').onclick=()=>switchView('settings');$('contactSupport').onclick=()=>openModal('supportModal');$('notificationsButton').onclick=()=>{document.querySelector('.notification-dot').style.display='none';showToast('You’re all caught up')};$('revenueMore').onclick=()=>switchView('reports');$('dateRangeButton').onclick=()=>showToast('Showing this month');document.querySelector('.brand').onclick=event=>{event.preventDefault();switchView('dashboard')};
$('invoiceTaxRate').addEventListener('input',updateFormTotal);$('invoiceDiscount').addEventListener('input',updateFormTotal);$('invoiceSearch').addEventListener('input',renderInvoices);$('expenseSearch').addEventListener('input',renderExpenses);$('invoiceFilters').onclick=e=>{if(e.target.matches('button')){activeFilter=e.target.dataset.filter;document.querySelectorAll('#invoiceFilters button').forEach(b=>b.classList.toggle('active',b===e.target));renderInvoices()}};$('expenseFilters').onclick=e=>{if(e.target.matches('button')){activeExpenseFilter=e.target.dataset.filter;document.querySelectorAll('#expenseFilters button').forEach(b=>b.classList.toggle('active',b===e.target));renderExpenses()}};$('globalSearch').addEventListener('input',e=>{if(e.target.value){switchView('invoices');$('invoiceSearch').value=e.target.value;renderInvoices()}});
$('invoiceForm').onsubmit=async e=>{e.preventDefault();const items=[...document.querySelectorAll('.line-item')].map(line=>({description:line.querySelector('.line-desc').value,qty:+line.querySelector('.line-qty').value,unit:line.querySelector('.line-unit').value,rate:+line.querySelector('.line-rate').value})),payload={number:$('invoiceNumber').value,clientId:+$('invoiceClient').value,issue:$('issueDate').value,due:$('dueDate').value,taxRate:+$('invoiceTaxRate').value,discount:+$('invoiceDiscount').value,notes:$('invoiceNotes').value,paymentDetails:$('invoicePaymentDetails').value,items},edited=editingInvoiceId;try{await api(edited?`/api/invoices/${edited}`:'/api/invoices',{method:edited?'PUT':'POST',body:JSON.stringify(payload)});editingInvoiceId=null;closeModal('invoiceModal');e.target.reset();await reload();switchView('invoices');showToast(edited?'Invoice updated':'Invoice created as draft')}catch(error){showToast(error.message,true)}};
$('clientForm').onsubmit=async e=>{e.preventDefault();const edited=editingClientId,payload={name:$('clientName').value,email:$('clientEmail').value,address:$('clientAddress').value,vatNumber:$('clientVatNumber').value};try{await api(edited?`/api/clients/${edited}`:'/api/clients',{method:edited?'PUT':'POST',body:JSON.stringify(payload)});editingClientId=null;e.target.reset();closeModal('clientModal');await reload();switchView('clients');showToast(edited?'Client updated':'Client added')}catch(error){showToast(error.message,true)}};
$('expenseForm').onsubmit=async e=>{e.preventDefault();const edited=editingExpenseId,payload={reference:$('expenseNumber').value,vendor:$('expenseVendor').value,category:$('expenseCategory').value,date:$('expenseDate').value,due:$('expenseDueDate').value,amount:+$('expenseAmount').value,status:$('expenseStatus').value,notes:$('expenseNotes').value};try{await api(edited?`/api/expenses/${edited}`:'/api/expenses',{method:edited?'PUT':'POST',body:JSON.stringify(payload)});editingExpenseId=null;e.target.reset();closeModal('expenseModal');await reload();switchView('expenses');showToast(edited?'Expense updated':'Expense saved')}catch(error){showToast(error.message,true)}};
$('profileForm').onsubmit=async e=>{e.preventDefault();try{const result=await api('/api/profile',{method:'PUT',body:JSON.stringify({...profile,companyName:$('companyName').value,ownerName:$('ownerName').value,email:$('companyEmail').value,phone:$('companyPhone').value,taxId:$('companyTaxId').value,vatNumber:$('companyVatNumber').value,address:$('companyAddress').value,currency:$('companyCurrency').value})});profile=result.profile;money=createMoneyFormatter();populateProfileForm();renderAll();$('settingsSaved').textContent='Changes saved';showToast('Company profile updated')}catch(error){showToast(error.message,true)}};
$('companyLogo').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>400000){showToast('Choose a logo smaller than 400 KB',true);return}const reader=new FileReader();reader.onload=()=>{profile.logo=reader.result;$('logoPreview').innerHTML=logoMarkup()};reader.readAsDataURL(file)};$('removeLogo').onclick=()=>{profile.logo='';$('companyLogo').value='';$('logoPreview').innerHTML=logoMarkup()};
$('supportForm').onsubmit=e=>{e.preventDefault();location.href=`mailto:support@ledgeriq.app?subject=${encodeURIComponent('ledgerIQ support request')}&body=${encodeURIComponent($('supportMessage').value)}`;closeModal('supportModal')};
async function openCheckout(cycle){try{const result=await api('/api/billing/checkout',{method:'POST',body:JSON.stringify({cycle})});location.href=result.url}catch(error){showToast(error.message,true)}}$('monthlyBilling').onclick=()=>openCheckout('monthly');$('annualBilling').onclick=()=>openCheckout('annual');$('exportAccount').onclick=async()=>{try{const data=await api('/api/account/export');download(`ledgeriq-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2));showToast('Complete data backup downloaded')}catch(error){showToast(error.message,true)}};$('deleteAccount').onclick=async()=>{if(!confirm('This permanently deletes your workspace, invoices and clients. Continue?'))return;const password=prompt('Enter your password to confirm');if(!password)return;try{await api('/api/account',{method:'DELETE',body:JSON.stringify({password})});location.reload()}catch(error){showToast(error.message,true)}};$('logoutButton').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()};
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();$('globalSearch').focus()}if(event.key==='Escape')document.querySelectorAll('.modal-backdrop.open').forEach(m=>closeModal(m.id))});
$('todayLabel').textContent=new Intl.DateTimeFormat('en-ZA',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase();
start();
