const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const {syncProvider} = require('./provider-adapters');
const {createStorage} = require('./storage');
const {assertSafeOutboundUrl,safeWebhookRequest} = require('./network-security');

const ROLES=['owner','admin','finance_manager','approver','accountant','employee','viewer'];
const PERMISSIONS={
 owner:['*'],admin:['manage_org','manage_team','manage_integrations','manage_finance','approve','audit','api'],
 finance_manager:['manage_finance','approve','manage_integrations','audit'],approver:['approve','audit'],
 accountant:['manage_finance','audit'],employee:['submit'],viewer:[]
};

function initEnterprise(db,h){
 const {send,fail,body,clean,now,id,email,hash,operationalState=()=>({}),clientIp=req=>req.socket?.remoteAddress||''}=h;
 const storage=createStorage();
 db.exec(`
 CREATE TABLE IF NOT EXISTS organizations (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name TEXT NOT NULL,
  legal_name TEXT NOT NULL DEFAULT '',registration_number TEXT NOT NULL DEFAULT '',vat_number TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',currency TEXT NOT NULL DEFAULT 'ZAR',
  logo TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL
 );
 CREATE INDEX IF NOT EXISTS idx_org_tenant ON organizations(tenant_id);
 CREATE TABLE IF NOT EXISTS memberships (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(organization_id,user_id)
 );
 CREATE INDEX IF NOT EXISTS idx_membership_user ON memberships(user_id);
 CREATE TABLE IF NOT EXISTS invitations (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  email TEXT NOT NULL,role TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,accepted_at TEXT,invited_by TEXT NOT NULL,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,tenant_id TEXT NOT NULL,organization_id TEXT,user_id TEXT,user_email TEXT NOT NULL,
  action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,details TEXT NOT NULL DEFAULT '{}',ip_address TEXT,created_at TEXT NOT NULL
 );
 CREATE INDEX IF NOT EXISTS idx_audit_tenant_time ON audit_logs(tenant_id,created_at DESC);
 CREATE TABLE IF NOT EXISTS approval_requests (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,
  amount REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'pending',requested_by TEXT NOT NULL,decided_by TEXT,decision_note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,decided_at TEXT
 );
 CREATE INDEX IF NOT EXISTS idx_approval_org ON approval_requests(organization_id,status);
 CREATE TABLE IF NOT EXISTS integration_connections (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,category TEXT NOT NULL,provider TEXT NOT NULL,
  display_name TEXT NOT NULL,encrypted_credentials TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',last_sync_at TEXT,last_error TEXT,created_at TEXT NOT NULL,UNIQUE(organization_id,category,provider)
 );
 CREATE TABLE IF NOT EXISTS bank_accounts (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,connection_id TEXT REFERENCES integration_connections(id) ON DELETE SET NULL,
  provider_account_id TEXT,name TEXT NOT NULL,account_number_masked TEXT NOT NULL DEFAULT '',currency TEXT NOT NULL,balance REAL NOT NULL DEFAULT 0,last_synced_at TEXT,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS bank_transactions (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,bank_account_id TEXT NOT NULL REFERENCES bank_accounts(id) ON DELETE CASCADE,
  provider_transaction_id TEXT,transaction_date TEXT NOT NULL,description TEXT NOT NULL,amount REAL NOT NULL,currency TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'unmatched',matched_type TEXT,matched_id TEXT,created_at TEXT NOT NULL,UNIQUE(bank_account_id,provider_transaction_id)
 );
 CREATE INDEX IF NOT EXISTS idx_bank_tx_org ON bank_transactions(organization_id,status,transaction_date DESC);
 CREATE TABLE IF NOT EXISTS payroll_runs (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,provider TEXT NOT NULL,period_start TEXT NOT NULL,period_end TEXT NOT NULL,
  gross REAL NOT NULL DEFAULT 0,tax REAL NOT NULL DEFAULT 0,net REAL NOT NULL DEFAULT 0,employee_count INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'draft',external_id TEXT,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS business_documents (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,type TEXT NOT NULL,number TEXT NOT NULL,counterparty TEXT NOT NULL,
  issue_date TEXT NOT NULL,status TEXT NOT NULL,total REAL NOT NULL DEFAULT 0,currency TEXT NOT NULL,payload TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(organization_id,type,number)
 );
 CREATE INDEX IF NOT EXISTS idx_docs_org_type ON business_documents(organization_id,type,created_at DESC);
 CREATE TABLE IF NOT EXISTS recurring_templates (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,name TEXT NOT NULL,frequency TEXT NOT NULL,next_run_date TEXT NOT NULL,
  template_type TEXT NOT NULL,payload TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS stored_files (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,
  original_name TEXT NOT NULL,storage_name TEXT NOT NULL,mime_type TEXT NOT NULL,size INTEGER NOT NULL,uploaded_by TEXT NOT NULL,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS api_keys (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,name TEXT NOT NULL,key_prefix TEXT NOT NULL,key_hash TEXT NOT NULL UNIQUE,
  scopes TEXT NOT NULL,created_by TEXT NOT NULL,last_used_at TEXT,revoked_at TEXT,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS webhook_endpoints (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,url TEXT NOT NULL,secret_hash TEXT NOT NULL,events TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS background_jobs (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',
  attempts INTEGER NOT NULL DEFAULT 0,run_after TEXT NOT NULL,last_error TEXT,created_at TEXT NOT NULL,completed_at TEXT
 );
 CREATE TABLE IF NOT EXISTS integration_snapshots (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,connection_id TEXT NOT NULL REFERENCES integration_connections(id) ON DELETE CASCADE,
  resource_type TEXT NOT NULL,record_count INTEGER NOT NULL DEFAULT 0,payload TEXT NOT NULL,created_at TEXT NOT NULL
 );
 CREATE INDEX IF NOT EXISTS idx_integration_snapshots ON integration_snapshots(connection_id,created_at DESC);
 CREATE TABLE IF NOT EXISTS approval_rules (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,entity_type TEXT NOT NULL,min_amount REAL NOT NULL DEFAULT 0,
  required_approvals INTEGER NOT NULL DEFAULT 1,active INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS approval_decisions (
  id TEXT PRIMARY KEY,request_id TEXT NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,user_id TEXT NOT NULL,decision TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,UNIQUE(request_id,user_id)
 );
 CREATE TABLE IF NOT EXISTS notifications (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,user_id TEXT NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,link TEXT NOT NULL DEFAULT '',read_at TEXT,created_at TEXT NOT NULL
 );
 CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,read_at,created_at DESC);
 CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id TEXT PRIMARY KEY,endpoint_id TEXT NOT NULL,event TEXT NOT NULL,status TEXT NOT NULL,http_status INTEGER,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,created_at TEXT NOT NULL,delivered_at TEXT
 );
 CREATE TABLE IF NOT EXISTS oauth_states (
  state_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,provider TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL
 );
 CREATE TABLE IF NOT EXISTS chart_accounts (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,UNIQUE(organization_id,code)
 );
 CREATE TABLE IF NOT EXISTS journal_entries (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,reference TEXT NOT NULL,entry_date TEXT NOT NULL,memo TEXT NOT NULL DEFAULT '',source TEXT NOT NULL DEFAULT 'manual',posted_by TEXT NOT NULL,posted_at TEXT NOT NULL,UNIQUE(organization_id,reference)
 );
 CREATE TABLE IF NOT EXISTS journal_lines (
  id TEXT PRIMARY KEY,entry_id TEXT NOT NULL REFERENCES journal_entries(id) ON DELETE RESTRICT,account_id TEXT NOT NULL REFERENCES chart_accounts(id),description TEXT NOT NULL DEFAULT '',debit REAL NOT NULL DEFAULT 0,credit REAL NOT NULL DEFAULT 0
 );
 CREATE TABLE IF NOT EXISTS accounting_periods (
  id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,organization_id TEXT NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,locked_at TEXT,locked_by TEXT,created_at TEXT NOT NULL,UNIQUE(organization_id,start_date,end_date)
 );
 `);
 ensureColumn('users','active_organization_id','TEXT');
 for(const table of ['clients','invoices','expenses'])ensureColumn(table,'organization_id','TEXT');
 ensureColumn('approval_requests','required_approvals','INTEGER NOT NULL DEFAULT 1');
 ensureColumn('approval_requests','approval_count','INTEGER NOT NULL DEFAULT 0');
 ensureColumn('stored_files','checksum','TEXT NOT NULL DEFAULT \'\'');
 ensureColumn('invoice_items','unit','TEXT NOT NULL DEFAULT \'\'');
 migrateExisting();

 function ensureColumn(table,column,type){const columns=db.prepare(`PRAGMA table_info(${table})`).all().map(c=>c.name);if(!columns.includes(column))db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${type}`);}
 function seedAccounts(tenantId,organizationId){const defaults=[['1000','Bank','asset'],['1100','Accounts receivable','asset'],['2000','Accounts payable','liability'],['2100','VAT payable','liability'],['3000','Owner equity','equity'],['4000','Sales','revenue'],['5000','Cost of sales','expense'],['6000','Operating expenses','expense']];const stmt=db.prepare(`INSERT OR IGNORE INTO chart_accounts(id,tenant_id,organization_id,code,name,type,created_at) VALUES(?,?,?,?,?,?,?)`);for(const [code,name,type] of defaults)stmt.run(id(),tenantId,organizationId,code,name,type,now())}
 function migrateExisting(){const tenants=db.prepare('SELECT * FROM tenants').all();for(const t of tenants){let org=db.prepare('SELECT id FROM organizations WHERE tenant_id=? ORDER BY created_at LIMIT 1').get(t.id);if(!org){org={id:id()};db.prepare(`INSERT INTO organizations(id,tenant_id,name,legal_name,registration_number,vat_number,email,phone,address,currency,logo,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(org.id,t.id,t.name,t.name,t.tax_id||'',t.vat_number||'',t.email||'',t.phone||'',t.address||'',t.currency||'ZAR',t.logo||'',now())}for(const u of db.prepare('SELECT id FROM users WHERE tenant_id=?').all(t.id)){db.prepare('UPDATE users SET active_organization_id=COALESCE(active_organization_id,?) WHERE id=?').run(org.id,u.id);db.prepare(`INSERT OR IGNORE INTO memberships(id,tenant_id,organization_id,user_id,role,created_at) VALUES(?,?,?,?,?,?)`).run(id(),t.id,org.id,u.id,'owner',now())}for(const table of ['clients','invoices','expenses'])db.prepare(`UPDATE ${table} SET organization_id=? WHERE tenant_id=? AND organization_id IS NULL`).run(org.id,t.id);for(const company of db.prepare('SELECT id FROM organizations WHERE tenant_id=?').all(t.id))seedAccounts(t.id,company.id)}}
 function createPrimaryOrganization(tenantId,userId,data){const orgId=id();db.prepare(`INSERT INTO organizations(id,tenant_id,name,legal_name,email,currency,created_at) VALUES(?,?,?,?,?,'ZAR',?)`).run(orgId,tenantId,clean(data.companyName,120),clean(data.companyName,120),email(data.email),now());db.prepare('UPDATE users SET active_organization_id=? WHERE id=?').run(orgId,userId);db.prepare('INSERT INTO memberships VALUES(?,?,?,?,?,?)').run(id(),tenantId,orgId,userId,'owner',now());seedAccounts(tenantId,orgId);return orgId;}
 function context(userId){return db.prepare(`SELECT u.active_organization_id organization_id,m.role,o.name organization_name FROM users u LEFT JOIN memberships m ON m.user_id=u.id AND m.organization_id=u.active_organization_id LEFT JOIN organizations o ON o.id=u.active_organization_id WHERE u.id=?`).get(userId)||{};}
 function permitted(user,permission){return user.role&&((PERMISSIONS[user.role]||[]).includes('*')||(PERMISSIONS[user.role]||[]).includes(permission));}
 function requirePermission(user,res,permission){if(!permitted(user,permission)){fail(res,403,'Your role does not allow this action');return false}return true;}
 function audit(user,action,entityType,entityId=null,details={},ip=''){db.prepare(`INSERT INTO audit_logs(tenant_id,organization_id,user_id,user_email,action,entity_type,entity_id,details,ip_address,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(user.tenant_id,user.organization_id||null,user.user_id||null,user.email||'system',action,entityType,entityId?String(entityId):null,JSON.stringify(details).slice(0,10000),ip||null,now());queueWebhook(user,`${entityType}.${action}`,{entityType,entityId,details});}
 function encrypt(value){const secret=String(process.env.INTEGRATION_ENCRYPTION_KEY||'');if(secret.length<32)throw new Error('INTEGRATION_ENCRYPTION_KEY must be configured before saving credentials');const key=crypto.createHash('sha256').update(secret).digest(),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return [iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),encrypted.toString('base64url')].join('.');}
 function decrypt(value){const secret=String(process.env.INTEGRATION_ENCRYPTION_KEY||''),[iv,tag,data]=String(value).split('.'),key=crypto.createHash('sha256').update(secret).digest(),decipher=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8'));}
 function notify(userId,tenantId,organizationId,title,message,link=''){db.prepare('INSERT INTO notifications VALUES(?,?,?,?,?,?,?,?,?)').run(id(),tenantId,organizationId,userId,clean(title,120),clean(message,500),clean(link,300),null,now())}
 function queueWebhook(user,event,payload){if(!user?.organization_id)return;const endpoints=db.prepare('SELECT id,events FROM webhook_endpoints WHERE organization_id=? AND active=1').all(user.organization_id);for(const endpoint of endpoints){const events=JSON.parse(endpoint.events||'["*"]');if(!events.includes('*')&&!events.includes(event))continue;const deliveryId=id();db.prepare('INSERT INTO webhook_deliveries VALUES(?,?,?,?,?,?,?,?,?)').run(deliveryId,endpoint.id,event,'queued',null,0,null,now(),null);db.prepare('INSERT INTO background_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id(),user.tenant_id,user.organization_id,'deliver_webhook',JSON.stringify({endpointId:endpoint.id,deliveryId,event,payload}), 'queued',0,now(),null,now(),null)}}
 function accountingSnapshot(organizationId){const accounts=db.prepare(`SELECT a.id,a.code,a.name,a.type,a.active,COALESCE(SUM(l.debit),0) debit,COALESCE(SUM(l.credit),0) credit FROM chart_accounts a LEFT JOIN journal_lines l ON l.account_id=a.id WHERE a.organization_id=? GROUP BY a.id ORDER BY a.code`).all(organizationId).map(a=>({...a,balance:['liability','equity','revenue'].includes(a.type)?a.credit-a.debit:a.debit-a.credit})),journals=db.prepare(`SELECT e.id,e.reference,e.entry_date entryDate,e.memo,e.source,e.posted_at postedAt,ROUND(SUM(l.debit),2) total FROM journal_entries e JOIN journal_lines l ON l.entry_id=e.id WHERE e.organization_id=? GROUP BY e.id ORDER BY e.entry_date DESC,e.posted_at DESC LIMIT 100`).all(organizationId),sum=type=>accounts.filter(a=>a.type===type).reduce((total,a)=>total+a.balance,0),revenue=sum('revenue'),expenses=sum('expense'),assets=sum('asset'),liabilities=sum('liability'),equity=sum('equity');return{accounts,journals,statements:{revenue,expenses,netProfit:revenue-expenses,assets,liabilities,equity,retainedEarnings:revenue-expenses,accountingEquationDifference:assets-(liabilities+equity+revenue-expenses)}}}
 function summary(user){
  const orgs=db.prepare(`SELECT o.*,m.role FROM organizations o JOIN memberships m ON m.organization_id=o.id WHERE m.user_id=? ORDER BY o.name`).all(user.user_id),members=db.prepare(`SELECT u.id,u.email,m.role,m.created_at createdAt FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? ORDER BY u.email`).all(user.organization_id),approvals=db.prepare(`SELECT * FROM approval_requests WHERE organization_id=? ORDER BY created_at DESC LIMIT 100`).all(user.organization_id),connections=db.prepare(`SELECT id,category,provider,display_name displayName,status,last_sync_at lastSyncAt,last_error lastError,created_at createdAt FROM integration_connections WHERE organization_id=? ORDER BY category,provider`).all(user.organization_id),accounts=db.prepare(`SELECT id,name,account_number_masked accountNumberMasked,currency,balance,last_synced_at lastSyncedAt FROM bank_accounts WHERE organization_id=?`).all(user.organization_id),transactions=db.prepare(`SELECT id,bank_account_id bankAccountId,transaction_date date,description,amount,currency,status,matched_type matchedType,matched_id matchedId FROM bank_transactions WHERE organization_id=? ORDER BY transaction_date DESC LIMIT 200`).all(user.organization_id),documents=db.prepare(`SELECT id,type,number,counterparty,issue_date issueDate,status,total,currency,created_at createdAt FROM business_documents WHERE organization_id=? ORDER BY created_at DESC LIMIT 100`).all(user.organization_id),payroll=db.prepare(`SELECT id,provider,period_start periodStart,period_end periodEnd,gross,tax,net,employee_count employeeCount,status,created_at createdAt FROM payroll_runs WHERE organization_id=? ORDER BY period_end DESC LIMIT 50`).all(user.organization_id),files=db.prepare(`SELECT id,entity_type entityType,entity_id entityId,original_name originalName,mime_type mimeType,size,created_at createdAt FROM stored_files WHERE organization_id=? ORDER BY created_at DESC LIMIT 100`).all(user.organization_id),recurring=db.prepare(`SELECT id,name,frequency,next_run_date nextRunDate,template_type templateType,active,created_at createdAt FROM recurring_templates WHERE organization_id=? ORDER BY created_at DESC`).all(user.organization_id),keys=db.prepare(`SELECT id,name,key_prefix keyPrefix,scopes,last_used_at lastUsedAt,revoked_at revokedAt,created_at createdAt FROM api_keys WHERE organization_id=? ORDER BY created_at DESC`).all(user.organization_id),webhooks=db.prepare(`SELECT id,url,events,active,created_at createdAt FROM webhook_endpoints WHERE organization_id=? ORDER BY created_at DESC`).all(user.organization_id);
  const approvalRules=db.prepare(`SELECT id,entity_type entityType,min_amount minAmount,required_approvals requiredApprovals,active FROM approval_rules WHERE organization_id=? ORDER BY entity_type,min_amount`).all(user.organization_id),notifications=db.prepare(`SELECT id,title,message,link,read_at readAt,created_at createdAt FROM notifications WHERE user_id=? AND organization_id=? ORDER BY created_at DESC LIMIT 50`).all(user.user_id,user.organization_id),webhookDeliveries=db.prepare(`SELECT d.id,d.event,d.status,d.http_status httpStatus,d.attempts,d.last_error lastError,d.created_at createdAt,d.delivered_at deliveredAt,e.url FROM webhook_deliveries d JOIN webhook_endpoints e ON e.id=d.endpoint_id WHERE e.organization_id=? ORDER BY d.created_at DESC LIMIT 50`).all(user.organization_id);
  const accounting=accountingSnapshot(user.organization_id);
  return{activeOrganizationId:user.organization_id,role:user.role,permissions:PERMISSIONS[user.role]||[],organizations:orgs,members,approvals,approvalRules,notifications,connections,bankAccounts:accounts,bankTransactions:transactions,documents,payrollRuns:payroll,files,recurring,apiKeys:keys,webhooks,webhookDeliveries,...accounting};
 }
 async function maybeSendInvite(invite,rawToken){if(!process.env.RESEND_API_KEY||!process.env.MAIL_FROM)return false;const origin=process.env.APP_ORIGIN||'http://localhost:3000',response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.MAIL_FROM,to:[invite.email],subject:'You are invited to ledgerIQ',html:`<p>You have been invited to ledgerIQ as ${invite.role}.</p><p><a href="${origin}/app?invite=${encodeURIComponent(rawToken)}">Accept invitation</a></p>`})});return response.ok;}
 async function handle(req,res,url,user){
  if(!url.pathname.startsWith('/api/enterprise/'))return false;
  const route=url.pathname.slice('/api/enterprise'.length),ip=clientIp(req);
  if(req.method==='GET'&&route==='/summary'){seedAccounts(user.tenant_id,user.organization_id);send(res,200,summary(user));return true;}
  if(req.method==='GET'&&route==='/audit'){if(!requirePermission(user,res,'audit'))return true;const rows=db.prepare(`SELECT id,user_email userEmail,action,entity_type entityType,entity_id entityId,details,ip_address ipAddress,created_at createdAt FROM audit_logs WHERE organization_id=? ORDER BY created_at DESC LIMIT 500`).all(user.organization_id).map(r=>({...r,details:JSON.parse(r.details||'{}')}));send(res,200,{audit:rows});return true;}
  if(req.method==='GET'&&route==='/readiness'){if(!requirePermission(user,res,'manage_org'))return true;const ops=operationalState(),checks=[['Production mode',process.env.NODE_ENV==='production'],['HTTPS application origin',String(process.env.APP_ORIGIN||'').startsWith('https://')],['Strong session secret',String(process.env.SESSION_SECRET||'').length>=32],['Credential encryption key',String(process.env.INTEGRATION_ENCRYPTION_KEY||'').length>=32],['Transactional email',Boolean(process.env.RESEND_API_KEY&&process.env.MAIL_FROM)],['Paystack billing',Boolean(process.env.PAYSTACK_SECRET_KEY&&process.env.PAYSTACK_MONTHLY_PLAN_CODE&&process.env.PAYSTACK_ANNUAL_PLAN_CODE)],['Durable document storage',Boolean(process.env.OBJECT_STORAGE_ENDPOINT||process.env.OBJECT_STORAGE_PATH)],['External monitoring delivery',Boolean(process.env.MONITORING_DSN&&ops.lastMonitoringSuccess)],['Encrypted offsite backup delivery',Boolean(process.env.OFFSITE_BACKUP_URL&&ops.lastBackupSuccess)]];send(res,200,{ready:checks.every(([,passed])=>passed),checks:checks.map(([name,passed])=>({name,passed}))});return true;}
  if(req.method==='POST'&&route==='/oauth/xero/start'){if(!requirePermission(user,res,'manage_integrations'))return true;if(!process.env.XERO_CLIENT_ID||!process.env.XERO_REDIRECT_URI){fail(res,503,'Xero OAuth environment variables are not configured');return true}const raw=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO oauth_states VALUES(?,?,?,?,?,?,?)').run(hash(raw),user.user_id,user.tenant_id,user.organization_id,'xero',new Date(Date.now()+10*60000).toISOString(),now());const params=new URLSearchParams({response_type:'code',client_id:process.env.XERO_CLIENT_ID,redirect_uri:process.env.XERO_REDIRECT_URI,scope:'openid profile email offline_access accounting.contacts.read accounting.transactions.read accounting.settings.read',state:raw});send(res,200,{url:`https://login.xero.com/identity/connect/authorize?${params}`});return true;}
  if(req.method==='GET'&&route==='/oauth/xero/callback'){if(!process.env.XERO_CLIENT_ID||!process.env.XERO_CLIENT_SECRET||!process.env.XERO_REDIRECT_URI){fail(res,503,'Xero OAuth environment variables are not configured');return true}const state=db.prepare(`SELECT * FROM oauth_states WHERE state_hash=? AND user_id=? AND organization_id=? AND expires_at>?`).get(hash(clean(url.searchParams.get('state'),200)),user.user_id,user.organization_id,now()),code=clean(url.searchParams.get('code'),1000);if(!state||!code){fail(res,400,'Xero authorisation is invalid or expired');return true}const form=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:process.env.XERO_REDIRECT_URI}),tokenResponse=await fetch('https://identity.xero.com/connect/token',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${process.env.XERO_CLIENT_ID}:${process.env.XERO_CLIENT_SECRET}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:form}),tokens=await tokenResponse.json().catch(()=>({}));if(!tokenResponse.ok||!tokens.access_token){fail(res,502,'Xero rejected the authorisation');return true}const tenantResponse=await fetch('https://api.xero.com/connections',{headers:{Authorization:`Bearer ${tokens.access_token}`,Accept:'application/json'}}),tenants=await tenantResponse.json().catch(()=>[]),tenant=tenants[0];if(!tenantResponse.ok||!tenant?.tenantId){fail(res,502,'No Xero organisation was authorised');return true}const credentials=encrypt({accessToken:tokens.access_token,refreshToken:tokens.refresh_token,expiresAt:new Date(Date.now()+Number(tokens.expires_in||1800)*1000).toISOString(),tenantId:tenant.tenantId}),existing=db.prepare(`SELECT id FROM integration_connections WHERE organization_id=? AND lower(provider)='xero'`).get(user.organization_id);if(existing)db.prepare(`UPDATE integration_connections SET encrypted_credentials=?,status='connected',display_name=?,last_error=NULL WHERE id=?`).run(credentials,`Xero · ${clean(tenant.tenantName,80)}`,existing.id);else db.prepare(`INSERT INTO integration_connections(id,tenant_id,organization_id,category,provider,display_name,encrypted_credentials,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id(),user.tenant_id,user.organization_id,'accounting','xero',`Xero · ${clean(tenant.tenantName,80)}`,credentials,'connected',now());db.prepare('DELETE FROM oauth_states WHERE state_hash=?').run(state.state_hash);audit(user,'authorised','integration',existing?.id||tenant.tenantId,{provider:'xero'},ip);res.writeHead(302,{Location:'/app?xero=connected'});res.end();return true;}
  if(req.method==='POST'&&route==='/organizations'){if(!requirePermission(user,res,'manage_org'))return true;const d=await body(req),name=clean(d.name,120);if(!name){fail(res,400,'Company name is required');return true}const orgId=id();db.prepare(`INSERT INTO organizations(id,tenant_id,name,legal_name,registration_number,vat_number,email,phone,address,currency,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(orgId,user.tenant_id,name,clean(d.legalName||name,160),clean(d.registrationNumber,80),clean(d.vatNumber,80),email(d.email)||'',clean(d.phone,40),clean(d.address,500),clean(d.currency,3)||'ZAR',now());db.prepare('INSERT INTO memberships VALUES(?,?,?,?,?,?)').run(id(),user.tenant_id,orgId,user.user_id,'owner',now());audit(user,'created','organization',orgId,{name},ip);send(res,201,{id:orgId});return true;}
  if(req.method==='POST'&&route==='/organizations/switch'){const d=await body(req),membership=db.prepare('SELECT role FROM memberships WHERE user_id=? AND organization_id=?').get(user.user_id,clean(d.organizationId,80));if(!membership){fail(res,403,'You do not belong to that company');return true}db.prepare('UPDATE users SET active_organization_id=? WHERE id=?').run(clean(d.organizationId,80),user.user_id);send(res,200,{ok:true});return true;}
  if(req.method==='POST'&&route==='/invitations'){if(!requirePermission(user,res,'manage_team'))return true;const d=await body(req),inviteEmail=email(d.email),role=clean(d.role,30);if(!inviteEmail||!ROLES.includes(role)||role==='owner'){fail(res,400,'Use a valid email and assignable role');return true}const raw=crypto.randomBytes(24).toString('base64url'),invite={id:id(),email:inviteEmail,role};db.prepare(`INSERT INTO invitations(id,tenant_id,organization_id,email,role,token_hash,expires_at,invited_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(invite.id,user.tenant_id,user.organization_id,inviteEmail,role,hash(raw),new Date(Date.now()+7*86400000).toISOString(),user.user_id,now());const sent=await maybeSendInvite(invite,raw);audit(user,'invited','member',invite.id,{email:inviteEmail,role},ip);send(res,201,{id:invite.id,sent,...(!sent?{inviteToken:raw}: {})});return true;}
  if(req.method==='POST'&&route==='/invitations/accept'){const d=await body(req),invite=db.prepare(`SELECT * FROM invitations WHERE token_hash=? AND accepted_at IS NULL AND expires_at>?`).get(hash(clean(d.token,200)),now());if(!invite||invite.email.toLowerCase()!==user.email.toLowerCase()){fail(res,400,'Invitation is invalid, expired, or belongs to another email');return true}db.prepare(`INSERT OR IGNORE INTO memberships(id,tenant_id,organization_id,user_id,role,created_at) VALUES(?,?,?,?,?,?)`).run(id(),invite.tenant_id,invite.organization_id,user.user_id,invite.role,now());db.prepare('UPDATE invitations SET accepted_at=? WHERE id=?').run(now(),invite.id);db.prepare('UPDATE users SET active_organization_id=? WHERE id=?').run(invite.organization_id,user.user_id);audit({...user,tenant_id:invite.tenant_id,organization_id:invite.organization_id},'accepted','invitation',invite.id,{},ip);send(res,200,{ok:true});return true;}
  let match=route.match(/^\/members\/([^/]+)$/);
  if(match&&req.method==='PATCH'){if(!requirePermission(user,res,'manage_team'))return true;const d=await body(req),role=clean(d.role,30);if(!ROLES.includes(role)||role==='owner'){fail(res,400,'Invalid assignable role');return true}const target=db.prepare('SELECT role FROM memberships WHERE user_id=? AND organization_id=?').get(match[1],user.organization_id);if(!target||target.role==='owner'){fail(res,403,'Owner role cannot be changed here');return true}db.prepare('UPDATE memberships SET role=? WHERE user_id=? AND organization_id=?').run(role,match[1],user.organization_id);audit(user,'role_changed','member',match[1],{role},ip);send(res,200,{ok:true});return true;}
  if(match&&req.method==='DELETE'){if(!requirePermission(user,res,'manage_team'))return true;if(match[1]===user.user_id){fail(res,400,'You cannot remove yourself');return true}const target=db.prepare('SELECT role FROM memberships WHERE user_id=? AND organization_id=?').get(match[1],user.organization_id);if(!target){fail(res,404,'Member not found');return true}if(target.role==='owner'){fail(res,403,'Owner cannot be removed');return true}db.prepare('DELETE FROM memberships WHERE user_id=? AND organization_id=?').run(match[1],user.organization_id);audit(user,'removed','member',match[1],{},ip);send(res,200,{ok:true});return true;}
  if(req.method==='POST'&&route==='/approvals'){if(!permitted(user,'submit')&&!permitted(user,'manage_finance')){fail(res,403,'Your role does not allow this action');return true}const d=await body(req),entityType=clean(d.entityType,40),entityId=clean(d.entityId,80),amount=Number(d.amount||0);if(!['invoice','expense','purchase_order','payroll_run'].includes(entityType)||!entityId||!Number.isFinite(amount)){fail(res,400,'Invalid approval request');return true}const rule=db.prepare(`SELECT MAX(required_approvals) required FROM approval_rules WHERE organization_id=? AND active=1 AND (entity_type=? OR entity_type='all') AND min_amount<=?`).get(user.organization_id,entityType,amount),required=Math.max(1,Math.min(5,Number(rule?.required||1))),requestId=id();db.prepare(`INSERT INTO approval_requests(id,tenant_id,organization_id,entity_type,entity_id,amount,requested_by,created_at,required_approvals,approval_count) VALUES(?,?,?,?,?,?,?,?,?,0)`).run(requestId,user.tenant_id,user.organization_id,entityType,entityId,amount,user.user_id,now(),required);for(const approver of db.prepare(`SELECT DISTINCT user_id FROM memberships WHERE organization_id=? AND role IN ('owner','admin','finance_manager','approver') AND user_id<>?`).all(user.organization_id,user.user_id))notify(approver.user_id,user.tenant_id,user.organization_id,'Approval requested',`${entityType.replaceAll('_',' ')} for ${amount.toFixed(2)} needs ${required} approval${required===1?'':'s'}.`,'enterprise');audit(user,'requested','approval',requestId,{entityType,entityId,amount,required},ip);send(res,201,{id:requestId,requiredApprovals:required});return true;}
  match=route.match(/^\/approvals\/([^/]+)$/);
  if(match&&req.method==='PATCH'&&db.prepare('SELECT 1 FROM approval_requests WHERE id=? AND requested_by=?').get(match[1],user.user_id)){fail(res,403,'Requesters cannot approve their own submission');return true}
  if(match&&req.method==='PATCH'){if(!requirePermission(user,res,'approve'))return true;const d=await body(req),decision=clean(d.status,20),request=db.prepare(`SELECT * FROM approval_requests WHERE id=? AND organization_id=? AND status='pending'`).get(match[1],user.organization_id);if(!request||!['approved','rejected'].includes(decision)){fail(res,404,'Pending request or valid decision not found');return true}try{db.prepare('INSERT INTO approval_decisions VALUES(?,?,?,?,?,?)').run(id(),request.id,user.user_id,decision,clean(d.note,500),now())}catch{fail(res,409,'You already decided this request');return true}if(decision==='rejected')db.prepare(`UPDATE approval_requests SET status='rejected',decided_by=?,decision_note=?,decided_at=? WHERE id=?`).run(user.user_id,clean(d.note,500),now(),request.id);else{const count=db.prepare(`SELECT COUNT(*) count FROM approval_decisions WHERE request_id=? AND decision='approved'`).get(request.id).count,status=count>=request.required_approvals?'approved':'pending';db.prepare(`UPDATE approval_requests SET approval_count=?,status=?,decided_by=CASE WHEN ?='approved' THEN ? ELSE decided_by END,decision_note=CASE WHEN ?='approved' THEN ? ELSE decision_note END,decided_at=CASE WHEN ?='approved' THEN ? ELSE decided_at END WHERE id=?`).run(count,status,status,user.user_id,status,clean(d.note,500),status,now(),request.id)}const updated=db.prepare('SELECT * FROM approval_requests WHERE id=?').get(request.id);notify(request.requested_by,user.tenant_id,user.organization_id,`Approval ${updated.status}`,`${updated.entity_type.replaceAll('_',' ')} ${updated.entity_id}: ${updated.approval_count}/${updated.required_approvals} approvals.`,'enterprise');audit(user,decision,'approval',match[1],{note:clean(d.note,500),approvalCount:updated.approval_count,requiredApprovals:updated.required_approvals},ip);send(res,200,{ok:true,status:updated.status,approvalCount:updated.approval_count});return true;}
  if(req.method==='POST'&&route==='/approval-rules'){if(!requirePermission(user,res,'manage_org'))return true;const d=await body(req),entityType=clean(d.entityType,40),minimum=Number(d.minAmount),required=Number(d.requiredApprovals);if(!['all','invoice','expense','purchase_order','payroll_run'].includes(entityType)||!Number.isFinite(minimum)||minimum<0||!Number.isInteger(required)||required<1||required>5){fail(res,400,'Use a valid document type, amount and 1–5 approvers');return true}const ruleId=id();db.prepare('INSERT INTO approval_rules VALUES(?,?,?,?,?,?,?,?,?)').run(ruleId,user.tenant_id,user.organization_id,entityType,minimum,required,1,user.user_id,now());audit(user,'created','approval_rule',ruleId,{entityType,minimum,required},ip);send(res,201,{id:ruleId});return true;}
  match=route.match(/^\/approval-rules\/([^/]+)$/);if(match&&req.method==='DELETE'){if(!requirePermission(user,res,'manage_org'))return true;db.prepare('DELETE FROM approval_rules WHERE id=? AND organization_id=?').run(match[1],user.organization_id);audit(user,'deleted','approval_rule',match[1],{},ip);send(res,200,{ok:true});return true;}
  match=route.match(/^\/notifications\/([^/]+)\/read$/);if(match&&req.method==='POST'){db.prepare('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?').run(now(),match[1],user.user_id);send(res,200,{ok:true});return true;}
  if(req.method==='POST'&&route==='/notifications/read-all'){db.prepare('UPDATE notifications SET read_at=? WHERE user_id=? AND organization_id=? AND read_at IS NULL').run(now(),user.user_id,user.organization_id);send(res,200,{ok:true});return true;}
  if(req.method==='POST'&&route==='/connections'){if(!requirePermission(user,res,'manage_integrations'))return true;const d=await body(req),category=clean(d.category,30),provider=clean(d.provider,50),displayName=clean(d.displayName,100);if(!['banking','accounting','payroll','payments'].includes(category)||!provider||!displayName){fail(res,400,'Invalid connection');return true}let encrypted='';try{if(d.credentials&&Object.keys(d.credentials).length)encrypted=encrypt(d.credentials)}catch(error){fail(res,503,error.message);return true}const connectionId=id();try{db.prepare(`INSERT INTO integration_connections(id,tenant_id,organization_id,category,provider,display_name,encrypted_credentials,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(connectionId,user.tenant_id,user.organization_id,category,provider,displayName,encrypted,encrypted?'connected':'pending',now())}catch{fail(res,409,'This provider is already connected');return true}audit(user,'connected','integration',connectionId,{category,provider},ip);send(res,201,{id:connectionId,status:encrypted?'connected':'pending'});return true;}
  match=route.match(/^\/connections\/([^/]+)\/sync$/);
  if(match&&req.method==='POST'){if(!requirePermission(user,res,'manage_integrations'))return true;const connection=db.prepare('SELECT * FROM integration_connections WHERE id=? AND organization_id=?').get(match[1],user.organization_id);if(!connection){fail(res,404,'Connection not found');return true}const jobId=id();db.prepare('INSERT INTO background_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(jobId,user.tenant_id,user.organization_id,`sync_${connection.category}`,JSON.stringify({connectionId:connection.id}), 'queued',0,now(),null,now(),null);audit(user,'sync_queued','integration',connection.id,{},ip);send(res,202,{jobId});return true;}
  match=route.match(/^\/connections\/([^/]+)$/);
  if(match&&req.method==='PATCH'){if(!requirePermission(user,res,'manage_integrations'))return true;const d=await body(req);let encrypted;try{encrypted=encrypt(d.credentials||{})}catch(error){fail(res,503,error.message);return true}const result=db.prepare(`UPDATE integration_connections SET encrypted_credentials=?,status='connected',last_error=NULL WHERE id=? AND organization_id=?`).run(encrypted,match[1],user.organization_id);if(!result.changes){fail(res,404,'Connection not found');return true}audit(user,'configured','integration',match[1],{},ip);send(res,200,{ok:true});return true;}
  if(match&&req.method==='DELETE'){if(!requirePermission(user,res,'manage_integrations'))return true;const result=db.prepare(`UPDATE integration_connections SET encrypted_credentials='',status='disconnected',last_error=NULL WHERE id=? AND organization_id=?`).run(match[1],user.organization_id);if(!result.changes){fail(res,404,'Connection not found');return true}audit(user,'disconnected','integration',match[1],{},ip);send(res,200,{ok:true});return true;}
  if(req.method==='POST'&&route==='/bank-accounts'){if(!requirePermission(user,res,'manage_finance'))return true;const d=await body(req),name=clean(d.name,100),currency=clean(d.currency,3);if(!name||currency.length!==3){fail(res,400,'Account name and currency are required');return true}const accountId=id();db.prepare(`INSERT INTO bank_accounts(id,tenant_id,organization_id,connection_id,provider_account_id,name,account_number_masked,currency,balance,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(accountId,user.tenant_id,user.organization_id,d.connectionId||null,clean(d.providerAccountId,100)||null,name,clean(d.accountNumberMasked,30),currency,Number(d.balance||0),now());audit(user,'created','bank_account',accountId,{name},ip);send(res,201,{id:accountId});return true;}
  if(req.method==='POST'&&route==='/bank-transactions/import'){if(!requirePermission(user,res,'manage_finance'))return true;const d=await body(req),account=db.prepare('SELECT * FROM bank_accounts WHERE id=? AND organization_id=?').get(clean(d.bankAccountId,80),user.organization_id);if(!account||!Array.isArray(d.transactions)){fail(res,400,'Bank account and transactions are required');return true}const stmt=db.prepare(`INSERT OR IGNORE INTO bank_transactions(id,tenant_id,organization_id,bank_account_id,provider_transaction_id,transaction_date,description,amount,currency,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`);let imported=0;for(const tx of d.transactions.slice(0,1000)){const amount=Number(tx.amount);if(!/^\d{4}-\d{2}-\d{2}$/.test(String(tx.date))||!Number.isFinite(amount))continue;const result=stmt.run(id(),user.tenant_id,user.organization_id,account.id,clean(tx.externalId,120)||id(),tx.date,clean(tx.description,300),amount,clean(tx.currency,3)||account.currency,now());imported+=Number(result.changes)}audit(user,'imported','bank_transaction',account.id,{count:imported},ip);send(res,201,{imported});return true;}
  match=route.match(/^\/bank-transactions\/([^/]+)\/match$/);
  if(match&&req.method==='POST'){if(!requirePermission(user,res,'manage_finance'))return true;const d=await body(req),matchedType=clean(d.matchedType,30),matchedId=clean(d.matchedId,80);if(!['invoice','expense','payroll_run','other'].includes(matchedType)||!matchedId){fail(res,400,'Invalid match');return true}const result=db.prepare(`UPDATE bank_transactions SET status='matched',matched_type=?,matched_id=? WHERE id=? AND organization_id=?`).run(matchedType,matchedId,match[1],user.organization_id);if(!result.changes){fail(res,404,'Transaction not found');return true}audit(user,'matched','bank_transaction',match[1],{matchedType,matchedId},ip);send(res,200,{ok:true});return true;}
  if(req.method==='POST'&&route==='/accounts'){if(!requirePermission(user,res,'manage_finance'))return true;const d=await body(req),code=clean(d.code,20),name=clean(d.name,120),type=clean(d.type,20);if(!code||!name||!['asset','liability','equity','revenue','expense'].includes(type)){fail(res,400,'Account code, name and valid type are required');return true}const accountId=id();try{db.prepare(`INSERT INTO chart_accounts(id,tenant_id,organization_id,code,name,type,created_at) VALUES(?,?,?,?,?,?,?)`).run(accountId,user.tenant_id,user.organization_id,code,name,type,now())}catch{fail(res,409,'Account code already exists');return true}audit(user,'created','account',accountId,{code,name,type},ip);send(res,201,{id:accountId});return true;}
  if(req.method==='POST'&&route==='/journals'){if(!requirePermission(user,res,'manage_finance'))return true;const d=await body(req),reference=clean(d.reference,60),entryDate=clean(d.entryDate,10),lines=Array.isArray(d.lines)?d.lines.slice(0,100):[];if(!reference||!/^\d{4}-\d{2}-\d{2}$/.test(entryDate)||lines.length<2){fail(res,400,'Reference, date and at least two journal lines are required');return true}if(db.prepare(`SELECT 1 FROM accounting_periods WHERE organization_id=? AND locked_at IS NOT NULL AND ? BETWEEN start_date AND end_date`).get(user.organization_id,entryDate)){fail(res,409,'That accounting period is locked');return true}let debit=0,credit=0;for(const line of lines){line.debit=Number(line.debit||0);line.credit=Number(line.credit||0);if(line.debit<0||line.credit<0||(line.debit>0&&line.credit>0)||(!line.debit&&!line.credit)||!db.prepare('SELECT 1 FROM chart_accounts WHERE id=? AND organization_id=? AND active=1').get(clean(line.accountId,80),user.organization_id)){fail(res,400,'Each line needs one valid account and either a debit or credit');return true}debit+=line.debit;credit+=line.credit}if(Math.abs(debit-credit)>0.005){fail(res,400,'Journal is not balanced');return true}const entryId=id();try{db.exec('BEGIN IMMEDIATE');db.prepare(`INSERT INTO journal_entries VALUES(?,?,?,?,?,?,?,?,?)`).run(entryId,user.tenant_id,user.organization_id,reference,entryDate,clean(d.memo,500),clean(d.source,30)||'manual',user.user_id,now());const stmt=db.prepare('INSERT INTO journal_lines VALUES(?,?,?,?,?,?)');for(const line of lines)stmt.run(id(),entryId,clean(line.accountId,80),clean(line.description,200),line.debit,line.credit);db.exec('COMMIT')}catch(error){try{db.exec('ROLLBACK')}catch{}fail(res,400,String(error.message).includes('UNIQUE')?'Journal reference already exists':'Could not post journal');return true}audit(user,'posted','journal',entryId,{reference,debit},ip);send(res,201,{id:entryId,total:debit});return true;}
  if(req.method==='POST'&&route==='/accounting-periods/lock'){if(!requirePermission(user,res,'manage_org'))return true;const d=await body(req),start=clean(d.startDate,10),end=clean(d.endDate,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||end<start){fail(res,400,'Valid period dates are required');return true}const periodId=id();try{db.prepare(`INSERT INTO accounting_periods(id,tenant_id,organization_id,start_date,end_date,locked_at,locked_by,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(periodId,user.tenant_id,user.organization_id,start,end,now(),user.user_id,now())}catch{fail(res,409,'That period is already defined');return true}audit(user,'locked','accounting_period',periodId,{start,end},ip);send(res,201,{id:periodId});return true;}
  if(req.method==='POST'&&route==='/payroll-runs'){if(!requirePermission(user,res,'manage_finance'))return true;const d=await body(req),runId=id();db.prepare(`INSERT INTO payroll_runs(id,tenant_id,organization_id,provider,period_start,period_end,gross,tax,net,employee_count,status,external_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(runId,user.tenant_id,user.organization_id,clean(d.provider,50)||'manual',clean(d.periodStart,10),clean(d.periodEnd,10),Number(d.gross||0),Number(d.tax||0),Number(d.net||0),Number(d.employeeCount||0),clean(d.status,20)||'draft',clean(d.externalId,100)||null,now());audit(user,'created','payroll_run',runId,{periodEnd:d.periodEnd},ip);send(res,201,{id:runId});return true;}
  if(req.method==='POST'&&route==='/documents'){if(!requirePermission(user,res,'manage_finance'))return true;const d=await body(req),type=clean(d.type,30);if(!['quote','purchase_order','credit_note'].includes(type)||!clean(d.number,60)){fail(res,400,'Invalid business document');return true}const documentId=id();try{db.prepare(`INSERT INTO business_documents(id,tenant_id,organization_id,type,number,counterparty,issue_date,status,total,currency,payload,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(documentId,user.tenant_id,user.organization_id,type,clean(d.number,60),clean(d.counterparty,150),clean(d.issueDate,10),clean(d.status,30)||'draft',Number(d.total||0),clean(d.currency,3)||'ZAR',JSON.stringify(d.payload||{}).slice(0,100000),user.user_id,now())}catch{fail(res,409,'Document number already exists');return true}audit(user,'created',type,documentId,{number:d.number,total:d.total},ip);send(res,201,{id:documentId});return true;}
  if(req.method==='POST'&&route==='/recurring'){if(!requirePermission(user,res,'manage_finance'))return true;const d=await body(req);if(!['weekly','monthly','quarterly','yearly'].includes(d.frequency)||!['invoice','expense'].includes(d.templateType)){fail(res,400,'Invalid recurring template');return true}const templateId=id();db.prepare(`INSERT INTO recurring_templates(id,tenant_id,organization_id,name,frequency,next_run_date,template_type,payload,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(templateId,user.tenant_id,user.organization_id,clean(d.name,100),d.frequency,clean(d.nextRunDate,10),d.templateType,JSON.stringify(d.payload||{}).slice(0,100000),user.user_id,now());audit(user,'created','recurring_template',templateId,{frequency:d.frequency},ip);send(res,201,{id:templateId});return true;}
  if(req.method==='POST'&&route==='/files'){if(!permitted(user,'submit')&&!permitted(user,'manage_finance')){fail(res,403,'Your role does not allow this action');return true}const d=await body(req),raw=String(d.data||''),matchData=raw.match(/^data:([\w/+.-]+);base64,(.+)$/),allowedTypes=new Set(['application/pdf','image/png','image/jpeg','image/webp','text/plain','text/csv']);if(!matchData||!allowedTypes.has(matchData[1])){fail(res,400,'Upload a PDF, PNG, JPEG, WebP, TXT or CSV file');return true}const buffer=Buffer.from(matchData[2],'base64');if(!buffer.length||buffer.length>5*1024*1024){fail(res,413,'Files must contain data and are limited to 5 MB');return true}const fileId=id(),storageName=`${user.tenant_id}-${fileId}`,checksum=crypto.createHash('sha256').update(buffer).digest('hex');await storage.put(storageName,buffer,matchData[1]);db.prepare(`INSERT INTO stored_files(id,tenant_id,organization_id,entity_type,entity_id,original_name,storage_name,mime_type,size,uploaded_by,created_at,checksum) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(fileId,user.tenant_id,user.organization_id,clean(d.entityType,40),clean(d.entityId,80)||null,clean(d.name,180),storageName,matchData[1],buffer.length,user.user_id,now(),checksum);audit(user,'uploaded','file',fileId,{name:d.name,size:buffer.length,checksum},ip);send(res,201,{id:fileId,checksum});return true;}
  match=route.match(/^\/files\/([^/]+)$/);
  if(match&&req.method==='GET'){const file=db.prepare('SELECT * FROM stored_files WHERE id=? AND organization_id=?').get(match[1],user.organization_id);if(!file){fail(res,404,'File not found');return true}let data;try{data=await storage.get(file.storage_name)}catch{fail(res,404,'Stored file is unavailable');return true}res.writeHead(200,{'Content-Type':file.mime_type,'Content-Length':data.length,'Content-Disposition':`attachment; filename="${file.original_name.replace(/["\r\n]/g,'_')}"`,'Cache-Control':'private, no-store'});res.end(data);return true;}
  if(match&&req.method==='DELETE'){if(!requirePermission(user,res,'manage_finance'))return true;const file=db.prepare('SELECT * FROM stored_files WHERE id=? AND organization_id=?').get(match[1],user.organization_id);if(!file){fail(res,404,'File not found');return true}await storage.delete(file.storage_name);db.prepare('DELETE FROM stored_files WHERE id=?').run(file.id);audit(user,'deleted','file',file.id,{name:file.original_name},ip);send(res,200,{ok:true});return true;}
  if(req.method==='POST'&&route==='/api-keys'){if(!requirePermission(user,res,'api'))return true;const d=await body(req),raw=`lq_${crypto.randomBytes(28).toString('base64url')}`,keyId=id();db.prepare(`INSERT INTO api_keys(id,tenant_id,organization_id,name,key_prefix,key_hash,scopes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(keyId,user.tenant_id,user.organization_id,clean(d.name,100),raw.slice(0,11),hash(raw),JSON.stringify(Array.isArray(d.scopes)?d.scopes:['read']),user.user_id,now());audit(user,'created','api_key',keyId,{name:d.name},ip);send(res,201,{id:keyId,key:raw});return true;}
  if(req.method==='GET'&&route==='/api-keys'){if(!requirePermission(user,res,'api'))return true;send(res,200,{keys:db.prepare(`SELECT id,name,key_prefix keyPrefix,scopes,last_used_at lastUsedAt,revoked_at revokedAt,created_at createdAt FROM api_keys WHERE organization_id=? ORDER BY created_at DESC`).all(user.organization_id)});return true;}
  match=route.match(/^\/api-keys\/([^/]+)$/);if(match&&req.method==='DELETE'){if(!requirePermission(user,res,'api'))return true;db.prepare('UPDATE api_keys SET revoked_at=? WHERE id=? AND organization_id=?').run(now(),match[1],user.organization_id);audit(user,'revoked','api_key',match[1],{},ip);send(res,200,{ok:true});return true;}
  if(req.method==='POST'&&route==='/webhooks'){if(!requirePermission(user,res,'api'))return true;const d=await body(req);let endpoint;try{endpoint=await assertSafeOutboundUrl(d.url)}catch(error){fail(res,400,error.message||'Valid public HTTPS webhook URL required');return true}const secret=crypto.randomBytes(24).toString('base64url'),webhookId=id();let storedSecret;try{storedSecret=encrypt(secret)}catch(error){fail(res,503,error.message);return true}db.prepare(`INSERT INTO webhook_endpoints VALUES(?,?,?,?,?,?,?,?,?,?)`).run(webhookId,user.tenant_id,user.organization_id,endpoint.href,storedSecret,JSON.stringify(Array.isArray(d.events)?d.events:['*']),1,user.user_id,now());audit(user,'created','webhook',webhookId,{url:endpoint.origin},ip);send(res,201,{id:webhookId,secret});return true;}
  match=route.match(/^\/webhooks\/([^/]+)$/);if(match&&req.method==='DELETE'){if(!requirePermission(user,res,'api'))return true;db.prepare('UPDATE webhook_endpoints SET active=0 WHERE id=? AND organization_id=?').run(match[1],user.organization_id);audit(user,'disabled','webhook',match[1],{},ip);send(res,200,{ok:true});return true;}
  fail(res,404,'Enterprise endpoint not found');return true;
 }
  function advanceDate(value,frequency){const d=new Date(`${value}T12:00:00Z`);if(frequency==='weekly')d.setUTCDate(d.getUTCDate()+7);if(frequency==='monthly')d.setUTCMonth(d.getUTCMonth()+1);if(frequency==='quarterly')d.setUTCMonth(d.getUTCMonth()+3);if(frequency==='yearly')d.setUTCFullYear(d.getUTCFullYear()+1);return d.toISOString().slice(0,10)}
  function runRecurring(){const today=now().slice(0,10),templates=db.prepare(`SELECT * FROM recurring_templates WHERE active=1 AND next_run_date<=? LIMIT 50`).all(today);for(const template of templates){try{const p=JSON.parse(template.payload),reference=`${clean(p.prefix,20)||'AUTO'}-${today.replaceAll('-','')}-${template.id.slice(0,5)}`;if(template.template_type==='invoice'){const due=new Date(`${today}T12:00:00Z`);due.setUTCDate(due.getUTCDate()+Number(p.dueDays||14));const result=db.prepare(`INSERT INTO invoices(tenant_id,organization_id,number,client_id,issue_date,due_date,status,tax_rate,discount,notes,payment_details,created_at) VALUES(?,?,?,?,?,?,'draft',?,?,?,?,?)`).run(template.tenant_id,template.organization_id,reference,Number(p.clientId),today,due.toISOString().slice(0,10),Number(p.taxRate||0),Number(p.discount||0),clean(p.notes,1000),clean(p.paymentDetails,1000),now()),itemStmt=db.prepare('INSERT INTO invoice_items(invoice_id,description,quantity,rate,unit) VALUES(?,?,?,?,?)');for(const item of p.items||[])itemStmt.run(Number(result.lastInsertRowid),clean(item.description,300),Number(item.qty),Number(item.rate),clean(item.unit,30))}else{db.prepare(`INSERT INTO expenses(tenant_id,organization_id,reference,vendor,category,expense_date,due_date,amount,status,notes,created_at) VALUES(?,?,?,?,?,?,?,?,'due',?,?)`).run(template.tenant_id,template.organization_id,reference,clean(p.vendor,150),clean(p.category,80),today,today,Number(p.amount||0),clean(p.notes,1000),now())}db.prepare('UPDATE recurring_templates SET next_run_date=? WHERE id=?').run(advanceDate(template.next_run_date,template.frequency),template.id)}catch(error){db.prepare('UPDATE recurring_templates SET active=0 WHERE id=?').run(template.id)}}}
  async function runJobs(){
   runRecurring();
   const jobs=db.prepare(`SELECT * FROM background_jobs WHERE status='queued' AND run_after<=? ORDER BY created_at LIMIT 10`).all(now());
   for(const job of jobs){
    db.prepare(`UPDATE background_jobs SET status='running',attempts=attempts+1 WHERE id=?`).run(job.id);
    let payload={};
    try{
     payload=JSON.parse(job.payload);
     if(job.type==='deliver_webhook'){
      const endpoint=db.prepare('SELECT * FROM webhook_endpoints WHERE id=? AND active=1').get(payload.endpointId);
      if(endpoint){
       const data=JSON.stringify({id:payload.deliveryId||job.id,event:payload.event,createdAt:job.created_at,data:payload.payload}),webhookSecret=decrypt(endpoint.secret_hash),signature=crypto.createHmac('sha256',webhookSecret).update(data).digest('hex'),response=await safeWebhookRequest(endpoint.url,{headers:{'Content-Type':'application/json','X-LedgerIQ-Signature':signature,'X-LedgerIQ-Delivery':payload.deliveryId||job.id},body:data});
       if(payload.deliveryId)db.prepare(`UPDATE webhook_deliveries SET status=?,http_status=?,attempts=attempts+1,last_error=?,delivered_at=? WHERE id=?`).run(response.ok?'delivered':'failed',response.status,response.ok?null:`HTTP ${response.status}`,response.ok?now():null,payload.deliveryId);
       if(!response.ok)throw new Error(`Webhook returned ${response.status}`);
      }
     }else{
      const connectionId=payload.connectionId,connection=db.prepare('SELECT * FROM integration_connections WHERE id=?').get(connectionId);
      if(!connection||connection.status!=='connected')throw new Error('Provider credentials are not connected');
      const result=await syncProvider(connection,decrypt(connection.encrypted_credentials)),snapshot=result.data||{},serialized=JSON.stringify(snapshot),recordCount=Array.isArray(snapshot)?snapshot.length:Object.values(snapshot||{}).reduce((total,value)=>total+(Array.isArray(value)?value.length:0),0);
      if(Buffer.byteLength(serialized)>2*1024*1024)throw new Error('Provider result exceeds the 2 MB snapshot limit');
      db.prepare(`INSERT INTO integration_snapshots(id,tenant_id,organization_id,connection_id,resource_type,record_count,payload,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(id(),connection.tenant_id,connection.organization_id,connection.id,connection.category,recordCount,serialized,now());
      if(result.credentials)db.prepare('UPDATE integration_connections SET encrypted_credentials=? WHERE id=?').run(encrypt(result.credentials),connectionId);
      db.prepare(`UPDATE integration_connections SET last_sync_at=?,last_error=NULL WHERE id=?`).run(now(),connectionId);
     }
     db.prepare(`UPDATE background_jobs SET status='completed',completed_at=? WHERE id=?`).run(now(),job.id);
    }catch(error){
     const current=db.prepare('SELECT attempts FROM background_jobs WHERE id=?').get(job.id),message=String(error.message).slice(0,500);
     db.prepare(`UPDATE background_jobs SET status=?,last_error=?,run_after=? WHERE id=?`).run(current.attempts>=3?'failed':'queued',message,new Date(Date.now()+Math.min(current.attempts*60000,3600000)).toISOString(),job.id);
     if(payload.connectionId)db.prepare('UPDATE integration_connections SET last_error=? WHERE id=?').run(message,payload.connectionId);
     if(payload.deliveryId)db.prepare(`UPDATE webhook_deliveries SET status='failed',attempts=attempts+1,last_error=? WHERE id=?`).run(message,payload.deliveryId);
    }
   }
  }
 return{createPrimaryOrganization,context,permitted,requirePermission,audit,summary,handle,runJobs,ROLES};
}

module.exports={initEnterprise,ROLES};
